EDU-10330 23H2KR5 | Fix Checkout API  error
vtex/openapi-schemas pull request #1012
Opened 2023-10-18 20:40 UTC by geisecosta

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2023-10-19 13:45 UTC, julia-rabello requested changes

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Information about Available accounts."
```suggestion
                                                        "description": "Information about an available account."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Benefit identifiers."
```suggestion
                                                        "description": "Benefit identifier."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Benefit teasers."
```suggestion
                                                        "description": "Benefit teaser."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
>                                                      "description": "Installment options information.",
```suggestion
                                                    "description": "List of installment options.",

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Information about Available accounts."
Que informação? Nome da conta?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Accounts."
Account name?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Messages."
```suggestion
                                                "description": "Message."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Gifts."
```suggestion
                                                "description": "Gift."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Messages."
```suggestion
                                                "description": "Message."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                            "description": "Attachments information."
```suggestion
                                                            "description": "Attachment information."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Pickup points information."
```suggestion
                                                        "description": "Pickup point information."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Pickup points information."
Qual informação? Pickup point ID?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                    "description": "Seller merchant installments information.",
O que é seller merchant?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                        "description": "Installments information."
```suggestion
                                                                        "description": "Installment information."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                        "description": "Installments information."
Qual informação?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Information payment."
```suggestion
                                                        "description": "Payment information."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Gift card messages."
```suggestion
                                                        "description": "Gift card message."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Available accounts."
```suggestion
                                                        "description": "Available account."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Available accounts."
Account name?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Available tokens."
```suggestion
                                                        "description": "Available token."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Available tokens."
O que é esse token? Qual informação aparece aqui?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
>                                                  "availableAssociations": {
O que é association? Falta uma descrição melhor

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Available associations."
```suggestion
                                                        "description": "Available association."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Available accounts."
```suggestion
                                                "description": "Available account."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Available accounts."
Account name?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Messages."
```suggestion
                                                "description": "Message."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                            "description": "Attachments information."
```suggestion
                                                            "description": "Attachment information."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Benefits identifiers."
```suggestion
                                                        "description": "Benefit identifier."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Benefits teasers."
```suggestion
                                                        "description": "Benefit teaser."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Available accounts."
```suggestion
                                                "description": "Available account."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Available accounts."
Account name?

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                "description": "Messages."
```suggestion
                                                "description": "Message."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                            "description": "Attachments information."
```suggestion
                                                            "description": "Attachment information."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Benefits identifiers."
```suggestion
                                                        "description": "Benefit identifier."

```

2023-10-19 13:45 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                        "description": "Benefits teasers."
```suggestion
                                                        "description": "Benefit teaser."

```

2023-10-25 14:44 UTC, julia-rabello requested changes
Faltou dar uma olhada nas demais [sugestões](https://github.com/vtex/openapi-schemas/pull/1012/files)

2023-10-26 10:44 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                        "description": "Gift cards."
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:44 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                "description": "Accounts."
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:45 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                "description": "Gifts."
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:46 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                        "description": "Pickup points information."
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:46 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                                    "description": "Seller merchant installments information.",
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:46 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                                        "description": "Installments information."
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:47 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                        "description": "Available accounts."
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:47 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                        "description": "Available tokens."
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 10:47 UTC, geisecosta commented on VTEX - Checkout API.json
>                                                  "availableAssociations": {
Esta informação precisa ser obtida junto ao time de Checkout, para atualização da documentação posteriormente.

2023-10-26 14:25 UTC, julia-rabello approved these changes

2023-10-26 16:24 UTC, merged