23H2KR5 Master Data API v2
vtex/openapi-schemas pull request #1013
Opened 2023-10-19 20:48 UTC by julia-rabello

FYI: I will add information about permissions in a separate pull request.

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-11-07 20:01 UTC, karenkrieger requested changes
@julia-rabello  Resolver comentários e erros do spectral 🤖

2023-11-09 23:14 UTC, julia-rabello commented on VTEX - Master Data API - v2.json
> +                                            "type": "string"
Isso aqui é um exemplo, então não pode ter description. Foi bug do Spectral.

2023-11-17 19:03 UTC, karenkrieger requested changes
Resolver os erros do Spectral e adicionar as permissões em todos os endpoints

2023-11-21 14:00 UTC, julia-rabello commented
@karenkrieger na description do PR comentei que vou adicionar permissions em outro PR, ainda não tenho essa informação certinha! Sobre os comentários do Spectral, a maioria são bugs, se quiser dar uma olhada de novo

2023-11-21 19:55 UTC, karenkrieger approved these changes
LGTM

2023-11-21 20:50 UTC, merged