EDU-10350 23H2KR5 | Pricing Hub
vtex/openapi-schemas pull request #1038
Opened 2023-11-03 11:56 UTC by geisecosta

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2023-11-03 14:07 UTC, geisecosta commented on VTEX - Pricing Hub.json
> +                            "example": 0
Falso positivo da regra `request-body-properties-example` documentado [aqui](https://docs.google.com/document/d/1iM-B9sKDAnUUdJK1GSkqZefYWO6JdxF_D097F8yNoNs/edit?usp=sharing).

2023-11-03 14:20 UTC, geisecosta commented on VTEX - Pricing Hub.json
> +                        "example": false,
Falso positivo da regra `request-body-properties-example` documentado [aqui](https://docs.google.com/document/d/1iM-B9sKDAnUUdJK1GSkqZefYWO6JdxF_D097F8yNoNs/edit?usp=sharing).

2023-11-03 16:35 UTC, geisecosta commented
Este PR contém "Falsos positivos" detectados pelo spectral que foram registrados [aqui](https://docs.google.com/document/d/1iM-B9sKDAnUUdJK1GSkqZefYWO6JdxF_D097F8yNoNs/edit?usp=sharing).

2023-11-07 14:20 UTC, julia-rabello requested changes

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                            "description": "This is the seller ID for the item.",
```suggestion
                            "description": "Seller ID for the item.",
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                            "description": "This is the brand ID for the item.",
```suggestion
                            "description": "Brand ID for the item.",
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                            "description": "This is the sku id of the item that will be priced.",
```suggestion
                            "description": "ID of the SKU that will be priced.",
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                            "description": "This is the index of the item at Checkout's cart. It has to be unique in the items array.",
```suggestion
                            "description": "Index of the item at Checkout's cart. It has to be unique in the items array.",
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                "description": "The list of items that are to be priced by Pricing Hub.",
```suggestion
                "description": "List of items to be priced by Pricing Hub.",
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                        "description": "The customer's email address. If there is no value, use an empty string."
```suggestion
                        "description": "Customer's email address. If there is no value, use an empty string."
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                        "description": "Internal campaign name, represented by the `utmi_cp` value in the URL that led to the order. If there is no value, use `null`."
```suggestion
                        "example": "sale",
                        "description": "Internal campaign name, represented by the `utmi_cp` value in the URL that led to the order. If there is no value, use `null`.",
                        "nullable": true
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                        "description": "Medium that indicates what type of traffic the customer originated from, represented by the `utm_medium` value in the URL that led to the order. If there is no
```suggestion
                        "example": "social",
                        "description": "Medium that indicates what type of traffic the customer originated from, represented by the `utm_medium` value in the URL that led to the order. If there is no value, use `null`.",
                        "nullable": true
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                        "description": "Traffic source, indicates where the traffic originated from according to the `utm_source` value in the URL that led to the order. If there is no value, use `nu
```suggestion
                        "example": "facebook",
                        "description": "Traffic source, which indicates where the traffic originated from according to the `utm_source` value in the URL that led to the order. If there is no value, use `null`.",
                        "nullable": true
```

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
>                      {
Remover linhas 197 a 218 (appkey e apptoken). Documentamos esses parâmetros apenas em securitySchemes e security.

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
>                  "description": "This route facilitates setting up an external price source in Pricing Hub. It also allows you to activate or deactivate that source in a given account. \r\n\r\n>ℹ️ Thi
Adicionar permissões necessárias

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
>                          "schema": {
Remover linhas 65 até 85. Documentamos appkey e apptoken apenas em security e securitySchemes.

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +                "description": "This route retrieves and applies prices for the items that are passed in the request. Pricing Hub will select the pricing method that will be used for each item and wi
Adicionar permissões necessárias

2023-11-07 14:20 UTC, julia-rabello commented on VTEX - Pricing Hub.json
> +        "description": "> This feature is in closed beta, available only for selected customers. If you have any questions, contact our [Support](https://support.vtex.com/hc/en-us/requests). \r\n\r\n
Revisar description:
* adicionar index de endpoints.
* remover request body examples que já estiverem nos endpoints.
* transferir todas as informações de parâmetros para os endpoints e remover tabela.

2023-11-10 13:02 UTC, geisecosta commented on VTEX - Pricing Hub.json
>                  "description": "This route facilitates setting up an external price source in Pricing Hub. It also allows you to activate or deactivate that source in a given account. \r\n\r\n>ℹ️ Thi
Atuarei nas permissions em outra PR

2023-11-10 17:21 UTC, julia-rabello requested changes
Faltou dar uma olhada em algumas sugestões.

2023-11-10 20:26 UTC, julia-rabello approved these changes

2023-11-13 17:18 UTC, merged