EDU-10992  Fix-Create promotion or tax
vtex/openapi-schemas pull request #1045
Opened 2023-11-10 11:04 UTC by geisecosta

Para correção dos erros do spectral, será aberto uma nova PR.

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2023-11-10 14:06 UTC, julia-rabello requested changes

2023-11-10 14:06 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                        "description": "- The `skus` object needs to have a valid `id` attribute.\n-The `products` object needs to have a valid `id` attribute.\n-The `brands` object needs to have a v
No erro 400, a gente costuma usar a description `Bad request`. Em que formato vêm essas mensagens que você apontou na response? Pode colocar um exemplo aqui?

2023-11-21 13:51 UTC, julia-rabello requested changes
@geisecosta faltou corrigir os erros do Spectral.

2023-11-21 16:35 UTC, geisecosta commented
> @geisecosta faltou corrigir os erros do Spectral.

@julia-rabello, conforme coloquei na descrição deste PR: Para correção dos erros do spectral, será aberto uma nova PR.

2023-11-21 20:52 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "object",
adicionar description

2023-11-21 20:57 UTC, julia-rabello requested changes

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                                "type": "array",
adicionar description

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                                    "type": "string"
adicionar description

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                        "": [
o nome do array é isso mesmo? `""`

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                            "Error message"
Dar um exemplo válido de error message

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                                    "type": "string"
Error message.

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                                "type": "array",
Array with errors.

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                                    "type": "string"
Adicionar na description todas as possíveis error messages

2023-11-21 20:57 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                        "description": "Bad request.\n\nThe error message can vary as follows:\n- The `skus` object needs to have a valid `id` attribute.\n- The `products` object needs to have a vali
Essas mensagens podem estar na description do campo onde aparecem na response

2023-11-22 13:17 UTC, geisecosta commented on VTEX - Promotions & Taxes API.json
> +                                        "": [
Sim é isso mesmo, com base no exemplo que o Douglas me passou.

2023-11-23 19:03 UTC, julia-rabello approved these changes

2023-11-24 19:31 UTC, merged