Update Servers & Parameters & Security
vtex/openapi-schemas pull request #1046
Opened 2023-11-10 12:47 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to update Customer Credit API (KR5) (EDU-10331).

2023-11-10 17:40 UTC, julia-rabello requested changes
Além das sugestões, recomendo:

* Adicionar permissões necessárias para usar cada endpoint.
* Adicionar os parâmetros comuns (Content-Type, Accept, transactionId, entre outros) em components > parameters e referenciá-los onde forem utilizados, para evitar ter que repetir definições e exemplos múltiplas vezes ao longo do arquivo.

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                            "default": "insert identifier here"
```suggestion
                            "example": "12345"
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                "description": "Add an account holder. This new user can share the account's credit limit with users already registered on the account.",
```suggestion
                "description": "Adds an account holder. This new user can share the account's credit limit with users already registered on the account.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
>                          "schema": {
mudar `default` para `example` na linha 7309 e adicionar um exemplo em vez do texto

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                            "default": "insert identifier here"
```suggestion
                            "example": "12345"
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Statement identification. This is the same \"transactionId\" field you get from the [Account statements](https://developers.vtex.com/docs/api-reference/custome
```suggestion
                        "description": "Statement identification. This is the same `transactionId` value obtained from the [Account statements](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/accounts/-creditAccountId-) endpoint response body.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Simplified identification invoice's generate by the merchant (optional).It consists of a 8 digit random id (of numbers and letters) and the installment.",
```suggestion
                        "description": "Simplified identification invoice generated by the merchant (optional). It consists of an 8-digit random ID composed of numbers and letters and the installment.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Simplified identification invoice's generate by the merchant (optional).It consists of a 8 digit random id (of numbers and letters) and the installment.",
O que significa "and the installment"?

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Some observation about the invoice.",
```suggestion
                        "description": "Observation notes about the invoice.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Simplified identification invoice's generate by the merchant (optional).It consists of a 8 digit random id (of numbers and letters) and the installment.",
```suggestion
                        "description": "Simplified identification invoice generated by the merchant (optional). It consists of an 8-digit random ID composed of numbers and letters and the installment.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Indicates the status of which invoices should be searched for in the invoice list.. It must be completed with \"Paid\", \"Cancelled\" or \"Open\" value.",
```suggestion
                        "description": "Indicates the status of the invoices to be searched for. It must be completed with `Paid`, `Cancelled` or `Open`.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
>                              "type": "string",
```suggestion
                        "schema": {
                            "type": "string",
                            "enum": ["Paid", "Cancelled", "Open"],
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Indicates the value of which invoices should be searched for in the invoice list. It must be completed with a decimal value.",
```suggestion
                        "description": "Indicates the value of the invoices to be searched for. It must be completed with a decimal value.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Indicates the final position of the invoice to be searched in the invoice list. Example, if the value of \"from\" is equal to 1 and \"to\" is 300, information
```suggestion
                        "description": "Indicates the final position of the invoice to be searched in the invoice list. Example, if the value of `from` is equal to `1` and `to` is `300`, information from 300 invoices will be displayed in the response body of the request.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                        "description": "Indicates the starting position of the invoice to be searched in the invoice list. Example, value \"1\" indicates that the first invoice in the list will be re
```suggestion
                        "description": "Indicates the starting position of the invoice to be searched in the invoice list. Example, value `1` indicates that the first invoice in the list will be returned.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                "description": "Returns a list of invoices filtered by the query params informed in the request.\r\n\r\n>ℹ️ The query params can be used individually or combined.\r\n\r\n### Queries t
```suggestion
                "description": "Returns a list of invoices filtered by the query params informed in the request.\r\n\r\n>ℹ️ Query params can be used individually or combined.\r\n\r\n### Queries to filter results\r\n\r\n- **By the location of the invoices in the list (quantity of invoices)**: `?from={int}&to={int}`\r\n- **By creation date**: `?createdDateFrom={dateISO8601}&createDateTo={dateISO8601}`. The dates should be in ISO8601 format.\r\n- **By due date**: `?dueDateFrom={dateISO8601}&dueDateTo={dateISO8601}`. The dates should be in ISO8601 format.\r\n- **By value**: `?value={decimal}`\r\n- **By status**: `?status={string}`\r\n- **By Id**: `?friendlyId={string}`\r\n- **By observation**: `?observation={string}`\r\n- **By creditAccountId**: `?creditAccountId={creditAcountId}`\r\n\r\n### Combining filters\r\n\r\nYou can use the `op` query parameter to specify if filters will be evaluated as `AND` or `OR` for the query. The default behavior when there is more than one query parameter is `AND`.\r\n\r\nExample:\r\n\r\nFor the query `?value=100&status=Paid`, the criteria will build **value = 100 AND status = Paid**.\r\n\r\nFor the same query, adding the `op` parameter (`?value=100&status=Paid&op=or`), the criteria will build **value = 100 OR status = Paid**.",
```

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                "description": "Returns a list of invoices filtered by the query params informed in the request.\r\n\r\n>ℹ️ The query params can be used individually or combined.\r\n\r\n### Queries t
É possível chamar essa API sem usar query params?

2023-11-10 17:40 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +        "description": "With Customer Credit your store can enable **credit payments** through the checkout. You can also control **invoices** and the **credit limits** of your clients.\r\n\r\nLearn
```suggestion
        "description": "With Customer Credit your store can enable **credit payments** through the checkout. You can also control **invoices** and the **credit limits** of your clients.\r\n\r\nLearn more about Customer Credit in our [Help Center article](https://help.vtex.com/en/tracks/customer-credit-getting-started--1hCRg21lXYy2seOKgqQ2CC/36grlQ69NK6OCuioeekyCs).\r\n\r\nAdditionally, you can find more information on installment payments for an order in the `customData`  field found in the [Get Order](https://developers.vtex.com/docs/api-reference/orders-api#get-/api/oms/pvt/orders/-orderId-) endpoint of the Orders API. This includes the number of installments, amount and due dates.\r\n\r\nAll requests need an authorization header. This API allows two kinds of authorization:\r\n\r\n1. Authorization header containing the VTEX ID authentication token.\r\n2. VTEX Appkey and Apptoken headers.\r\n\r\nRead [Authentication](https://developers.vtex.com/docs/guides/authentication) for more information about authentication options.\r\n\r\n## Customer Credit API Index\r\n\r\n### Invoices\r\n\r\n- `GET` [Search all invoices](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/invoices)\r\n- `GET` [Retrieve Invoice by Id](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/accounts/-creditAccountId-/invoices/-invoiceId-)\r\n- `PUT` [Change Invoice](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-/invoices/-invoiceId-)\r\n- `DELETE` [Cancel Invoice](https://developers.vtex.com/docs/api-reference/customer-credit-api#delete-/api/creditcontrol/accounts/-creditAccountId-/invoices/-invoiceId-)\r\n- `GET` [Retrieve invoice by creditAccountId](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/accounts/-creditAccountId-/invoices)\r\n- `POST` [Mark an invoice as Paid](https://developers.vtex.com/docs/api-reference/customer-credit-api#post-/api/creditcontrol/accounts/-creditAccountId-/invoices/-invoiceId-/payments)\r\n- `PUT` [Postpone an invoice](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-/invoices/-invoiceId-/postponement)\r\n\r\n### Account\r\n\r\n- `GET` [Search all accounts](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/accounts)\r\n- `POST` [Open an Account](https://developers.vtex.com/docs/api-reference/customer-credit-api#post-/api/creditcontrol/accounts)\r\n- `GET` [Retrieve an Account by Id](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/accounts/-creditAccountId-)\r\n- `DELETE` [Close an Account](https://developers.vtex.com/docs/api-reference/customer-credit-api#delete-/api/creditcontrol/accounts/-creditAccountId-)\r\n- `PUT` [Update email and description of a account](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-)\r\n- `GET` [Account statements](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/accounts/-creditAccountId-/statements)\r\n- `PUT` [Open or Change Account](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-accountId-)\r\n- `PUT` [Change credit limit of an Account](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-/creditlimit)\r\n- `PUT` [Decrease balance of an account](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-/statements/-statementId-)\r\n- `PUT` [Create or Update Settlement](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-/transactions/-transactionId-/settlement)\r\n- `POST` [Create a Pre-Authorization](https://developers.vtex.com/docs/api-reference/customer-credit-api#post-/api/creditcontrol/accounts/-creditAccountId-/transaction)\r\n- `PUT` [Update a Pre-Authorization](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-/transactions/-transactionId-)\r\n- `DELETE` [Cancel a Pre-Authorization](https://developers.vtex.com/docs/api-reference/customer-credit-api#delete-/api/creditcontrol/accounts/-creditAccountId-/transactions/-transactionId-)\r\n- `POST` [Add an account Holder](https://developers.vtex.com/docs/api-reference/customer-credit-api#post-/api/creditcontrol/accounts/-creditAccountId-/holders)\r\n- `DELETE` [Delete an account holder](https://developers.vtex.com/docs/api-reference/customer-credit-api#delete-/api/creditcontrol/accounts/-creditAccountId-/holders/-holderId-)\r\n- `PUT` [Change tolerance of an account](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/accounts/-creditAccountId-/tolerance)\r\n- `POST` [Partial or Total Refund a Settlement](https://developers.vtex.com/docs/api-reference/customer-credit-api#post-/api/creditcontrol/accounts/-creditAccountId-/transactions/-transactionId-/refunds)\r\n\r\n### Store Configuration\r\n\r\n- `GET` [Retrieve store configuration](https://developers.vtex.com/docs/api-reference/customer-credit-api#get-/api/creditcontrol/storeconfig)\r\n- `PUT` [Create or change store configuration](https://developers.vtex.com/docs/api-reference/customer-credit-api#put-/api/creditcontrol/storeconfig)\r\n",
```

2023-11-24 21:04 UTC, julia-rabello requested changes
Não costumamos incluir headers não obrigatórios na documentação, mas, como essa informação já está aqui, todos precisam ter descrições.

Também percebi que existem muitos parâmetros, headers e estruturas de objetos repetidas. Recomendo adicionar todos os que se repetem como [components](https://swagger.io/docs/specification/components/) e referenciar, para evitar ter que ajustar as mesmas descrições em várias linhas diferentes.

2023-11-24 21:04 UTC, julia-rabello commented on VTEX - Customer Credit API.json
>                                              "type": "string"
adicionar description

2023-11-24 21:22 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
> +                        "description": "Indicates the starting position of the invoice to be searched in the invoice list. Example, value `1` indicates that the first invoice in the list will be retu
Corrigido.

2023-11-24 21:22 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
> +                            "example": 1
Corrigido.

2023-11-24 21:23 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
> +                        "description": "Indicates the final position of the invoice to be searched in the invoice list. Example, if the value of `from` is equal to `1` and `to` is `300`, information
Corrigido.

2023-11-24 21:47 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
> +                                                        "description": "Simplified identification of an invoice. This code is created automatically, always associated with an existing invoice and it
Corrigido.

2023-11-24 21:48 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
> +                                            "description": "Simplified identification of an invoice. This code is created automatically, always associated with an existing invoice and it consists of
Corrigido.

2023-11-24 21:49 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
> +                "description": "Updates invoice's attributes `status`, `observation` and `paymentLink`.\r\n\r\n## Permissions\r\n\r\nAny user or [application key](https:\/\/developers.vtex.com\/docs\
Corrigido.

2023-11-24 21:51 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
> +                "summary": "Retrieve invoice by creditAccountId",
Corrigido.

2023-11-24 21:54 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
>                                              "type": "string"
Estes "headers" foram documentados no passado na API, mas não temos certeza se são realmente necessários. Abri uma [thread](https://vtex.slack.com/archives/C0165UQ8SSE/p1699988587589999) no #team-payments-docs para discutir a remoção deles. Por ora, irei mantê-los mas sem realizar modificações.

2023-11-24 21:54 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
>                                              "type": "string"
Estes "headers" foram documentados no passado na API, mas não temos certeza se são realmente necessários. Abri uma [thread](https://vtex.slack.com/archives/C0165UQ8SSE/p1699988587589999) no #team-payments-docs para discutir a remoção deles. Por ora, irei mantê-los mas sem realizar modificações.

2023-11-24 21:54 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
>                                              "type": "string"
Estes "headers" foram documentados no passado na API, mas não temos certeza se são realmente necessários. Abri uma [thread](https://vtex.slack.com/archives/C0165UQ8SSE/p1699988587589999) no #team-payments-docs para discutir a remoção deles. Por ora, irei mantê-los mas sem realizar modificações.

2023-11-24 21:54 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
>                                              "type": "string"
Estes "headers" foram documentados no passado na API, mas não temos certeza se são realmente necessários. Abri uma [thread](https://vtex.slack.com/archives/C0165UQ8SSE/p1699988587589999) no #team-payments-docs para discutir a remoção deles. Por ora, irei mantê-los mas sem realizar modificações.

2023-11-24 21:55 UTC, ricardoaerobr commented on VTEX - Customer Credit API.json
>                                              "type": "string"
Estes "headers" foram documentados no passado na API, mas não temos certeza se são realmente necessários. Abri uma [thread](https://vtex.slack.com/archives/C0165UQ8SSE/p1699988587589999) no #team-payments-docs para discutir a remoção deles. Por ora, irei mantê-los mas sem realizar modificações.

2023-11-27 15:03 UTC, julia-rabello requested changes

2023-11-27 15:03 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                "summary": "Retrieve invoice by id",
```suggestion
                "summary": "Retrieve invoice by ID",
```

2023-11-27 15:03 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                "summary": "Retrieve an account by id",
```suggestion
                "summary": "Retrieve an account by ID",
```

2023-11-27 15:03 UTC, julia-rabello commented on VTEX - Customer Credit API.json
> +                                                            "example": "0"
```suggestion
                                                            "example": 0
```

2023-11-27 15:08 UTC, julia-rabello approved these changes

2023-11-27 15:10 UTC, merged