EDU-1024 | KR5 H2 - VTEX Headless CMS
vtex/openapi-schemas pull request #1048
Opened 2023-11-13 19:05 UTC by Mariana-Caetano

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2023-12-01 20:37 UTC, julia-rabello requested changes

2023-12-05 13:24 UTC, Mariana-Caetano commented on VTEX - Headless CMS API.json
>              "url": "https://{accountName}.myvtex.com",
@julia-rabello nesse caso do Headless CMS (e outras APIs de apps do IO) seria `myvtex.com`, mas parece que a questão é um pouco mais extensa como está sendo discutido [nesta thread](https://vtex.slack.com/archives/C02J700F525/p1701728421395899?thread_ts=1696342424.556039&cid=C02J700F525) e [nesta](https://vtex.slack.com/archives/C05CQFJ5TUH/p1701720951736899). 👀

2023-12-21 21:05 UTC, julia-rabello approved these changes

2023-12-21 21:12 UTC, julia-rabello approved these changes

2023-12-21 23:23 UTC, merged