Antifraud Provider Update Parameters & Headers
vtex/openapi-schemas pull request #1065
Opened 2023-12-05 18:13 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to update tje Antifraud Provider Protocol API:
1) Removal of unnecessary headers in documentation (https://vtex.slack.com/archives/C0165UQ8SSE/p1699988587589999).
2) Return of incorrectly removed parameters in PR-1037.

2023-12-05 18:39 UTC, karenkrieger requested changes

2023-12-05 18:56 UTC, ricardoaerobr commented on VTEX - Antifraud Provider API.json
> +                }
Boa. Revisado.

2023-12-05 20:49 UTC, karenkrieger requested changes

2023-12-05 20:49 UTC, karenkrieger commented on VTEX - Antifraud Provider API.json
>                  "description": "The AppKey configured by the merchant."
```suggestion
                "description": "Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
```

2023-12-05 20:49 UTC, karenkrieger commented on VTEX - Antifraud Provider API.json
>                  "description": "The AppToken configured by the merchant."
```suggestion
                "description": "Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys)."
```

2023-12-06 19:55 UTC, karenkrieger approved these changes
LGTM

2023-12-06 19:55 UTC, merged