KR5 | External Seller Fulfillment
vtex/openapi-schemas pull request #1074
Opened 2023-12-13 04:21 UTC by anabaarbosa

A descrição do campo OrderId está vazio pois ainda não consegui retorno do time de desenvolvimento.

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-12-13 15:35 UTC, karenkrieger requested changes

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                            "title": "A Schema",
```suggestion
```

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                            "description": "An explanation about the purpose of this instance.",
Adicionar descrição

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                                    "description": "Position of this item in the original array, i.e., in the array that came with the request. This index is what identifies which SKU you are referri
```suggestion
                                    "description": "Position of this item in the original array, i.e., in the array that came with the request. This index is what identifies which SKU you are referring to for each object inside the `logisticsInfo`.",
```

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                                        "description": "Array of country codes",
```suggestion
                                        "description": "Array of country codes.",
```

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                                                "description": "Contains the data about the pickup point. If you don’t want to send this, use the value `null`.",
```suggestion
                                                "description": "Contains the data about the pickup point. If you do not want to send this, use the value `null`.",
```

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                        "description": "Flag for permission of multiple deliveries",
```suggestion
                        "description": "Flag for permission of multiple deliveries.",
```

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                        "description": "",
Adicionar descrição

2023-12-13 15:35 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                "description": "ID of the order being fulfilled",
```suggestion
                "description": "ID of the order being fulfilled.",
```

2023-12-14 13:50 UTC, karenkrieger requested changes

2023-12-14 13:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                            "description": "An explanation about the purpose of this instance.",
Faltou esse comentário @anabaarbosa

2023-12-14 15:29 UTC, anabaarbosa commented on VTEX - Marketplace Protocol - External Seller Fulfillment.json
> +                            "description": "An explanation about the purpose of this instance.",
Pronto! Removi essa descrição, ela não é necessária, na verdade, tem descrição em cada um dos campos e no array.

2023-12-14 17:01 UTC, karenkrieger approved these changes
LGTM

2023-12-14 17:10 UTC, merged