EDU-10353-reviews-and-ratings
vtex/openapi-schemas pull request #1089
Opened 2023-12-21 13:24 UTC by Mariana-Caetano

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

2023-12-21 13:27 UTC, Mariana-Caetano commented on VTEX - Reviews and Ratings API.json
> -                "summary": "Create Multiple Reviews",
Deixar apenas o campo de `VtexidClientAutCookie` no schema de security para esse endpoint.

2023-12-21 13:56 UTC, julia-rabello requested changes

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +        "description": "\r\n[Reviews & Ratings](https://developers.vtex.com/vtex-developer-docs/docs/vtex-reviews-and-ratings) is a VTEX IO native solution that allows shoppers to submit reviews and
```suggestion
        "description": "[Reviews & Ratings](https://developers.vtex.com/vtex-developer-docs/docs/vtex-reviews-and-ratings) is a VTEX IO native solution that allows shoppers to submit reviews and ratings for products, and view them while navigating the store. With the Reviews and Ratings API you can manage the reviews and ratings associated with the products in your store. \r\n\r\n ## Index \r\n\r\n ### Rating\r\n\r\n- `GET` [Get Product Rating](https://developers.vtex.com/vtex-rest-api/reference/getproductrating)\r\n\r\n### Review\r\n\r\n- `GET` [Get Review by Review ID](https://developers.vtex.com/vtex-rest-api/reference/getreviewbyreviewid)\r\n- `DELETE` [Delete Review](https://developers.vtex.com/vtex-rest-api/reference/deletereview)\r\n- `PATCH` [Update a Review](https://developers.vtex.com/vtex-rest-api/reference/editreview)\r\n- `GET` [Get a list of Reviews](https://developers.vtex.com/vtex-rest-api/reference/getalistofreviews)\r\n- `POST` [Create Multiple Reviews](https://developers.vtex.com/vtex-rest-api/reference/savemultiplereviews)\r\n- `DELETE` [Delete Multiple Reviews](https://developers.vtex.com/vtex-rest-api/reference/deletemultiplereviews)\r\n- `POST` [Create a Review](https://developers.vtex.com/vtex-rest-api/reference/savereview)",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +        "description": "\r\n[Reviews & Ratings](https://developers.vtex.com/vtex-developer-docs/docs/vtex-reviews-and-ratings) is a VTEX IO native solution that allows shoppers to submit reviews and
VTEX IO native solution ou VTEX IO app? Deixar mais claro que precisa ter o app para usar

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +        "description": "\r\n[Reviews & Ratings](https://developers.vtex.com/vtex-developer-docs/docs/vtex-reviews-and-ratings) is a VTEX IO native solution that allows shoppers to submit reviews and
Importante atualizar todos os links para os endpoints (exemplo: `https://developers.vtex.com/vtex-rest-api/reference/getreviewbyreviewid` >> `https://developers.vtex.com/vtex-rest-api/reference/getreviewbyreviewid`)

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
>              "variables": {
Linha 11:
A url deve ser apenas `https://{accountName}.{environment}.com`. A parte `/reviews-and-ratings/api` deve ser incluída em todos os paths.

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +                        "headers": {},
```suggestion
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +                        "headers": {},
```suggestion
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +                        "content": {}
```suggestion
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
>                  "summary": "Get a list of Reviews",
```suggestion
                "summary": "Get list of reviews",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
>                  "summary": "Delete Review",
```suggestion
                "summary": "Delete review",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +                "summary": "Get product's review",
```suggestion
                "summary": "Get product review by review ID",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +                "description": "Retrieves information of a product review based on its ID.\r\n\r\n ## Permissions\r\n\r\nThis endpoint does not require [permissions](https://help.vtex.com/en/tutorial
```suggestion
                "description": "Retrieves information of a product review based on the review's ID.\r\n\r\n ## Permissions\r\n\r\nThis endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +                "description": "Creates a single review. \r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6zt
```suggestion
                "description": "Creates a single review. \r\n## Permissions\r\n\r\nThis endpoint does not require [permissions](https:\/\/help.vtex.com\/en\/tutorial\/license-manager-resources--3q6ztrC8YynQf6rdc6euk3). \r\n For authentication, you must generate and use only your `VtexidClientAutCookie` to work with this endpoint. Refer to the [Generating user tokens](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens#generating-a-user-token-with-the-vtex-io-cli) guide for more information.",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
>                  "summary": "Create a Review",
```suggestion
                "summary": "Create a review",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> +        },
```suggestion
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
>                          "description": "If the review was approved (`true`) or not (`false`).",
```suggestion
                        "description": "Defines if the review was approved (`true`) or not (`false`).",
```

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> -                    },
Como a API vai buscar as reviews relacionadas a um produto sem receber a product ID?

2023-12-21 13:56 UTC, julia-rabello commented on VTEX - Reviews and Ratings API.json
> -                "summary": "Create Multiple Reviews",
Esse é com VtexidClientAutCookie mesmo ou appKey + appToken? Create a single review é só com VtexidClientAutCookie, certo?

2023-12-21 13:59 UTC, Mariana-Caetano commented on VTEX - Reviews and Ratings API.json
> -                "summary": "Create Multiple Reviews",
Esse é o appKey + appToken. Confundi e na verdade esse comentário é para o "Create a single review"

2023-12-22 16:37 UTC, Mariana-Caetano commented on VTEX - Reviews and Ratings API.json
> -                    },
Apaguei essa parte, acredito que foi por engano 🤔mas já retornei com esse parâmetro.

2023-12-22 19:55 UTC, julia-rabello approved these changes

2023-12-22 20:11 UTC, merged