Update callouts about data retention
vtex/openapi-schemas pull request #1090
Opened 2023-12-21 15:08 UTC by Isabella-Veloso

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

There was another change in the data retention policy for retrieving orders from more than 2 years ago. Now, it is no longer possible to open a ticket for support for data requests, because VTEX doesn't store that information anymore. In those endpoints, there was the same callout about this, and I have removed a sentence that said it was possible to open a ticket.

2023-12-21 15:41 UTC, karenkrieger requested changes

2023-12-21 15:41 UTC, karenkrieger commented on VTEX - Orders API.json
> +                "description": "This endpoint retrieves order details by searching a specific order ID or sequence number. \r\n\r\n> You can only access information from orders created in the last tw
Remover o response body, melhor deixar ele só no schema, e adicionar as permissões na `description`

2023-12-21 15:41 UTC, karenkrieger commented on VTEX - Orders API.json
> +                "description": "Retrieves a list of orders according to the filters described below. \r\n\r\nThe limit of information retrieval is 30 pages, the default number of orders per page is 1
Adicionar premissões

2023-12-21 15:41 UTC, karenkrieger commented on VTEX - Orders API.json
> +                "description": "Lists all orders from a given customer, filtering by their email. \r\n\r\n> You can only access information from orders created in the last two years, and that same pe
Adicionar permissões

2023-12-21 15:41 UTC, karenkrieger commented on VTEX - Orders API.json
> +                "description": "Lists all details from an order, through the perspective of the customer who placed the order. \r\n\r\n> You can only access information from orders created in the las
Adicionar permissões

2023-12-22 12:54 UTC, Isabella-Veloso commented on VTEX - Orders API.json
> +                "description": "This endpoint retrieves order details by searching a specific order ID or sequence number. \r\n\r\n> You can only access information from orders created in the last tw
Ok, response body removido e permissões adicionadas.

2023-12-22 12:55 UTC, Isabella-Veloso commented on VTEX - Orders API.json
> +                "description": "Lists all orders from a given customer, filtering by their email. \r\n\r\n> You can only access information from orders created in the last two years, and that same pe
Ok, permissões adicionadas.

2023-12-22 12:55 UTC, Isabella-Veloso commented on VTEX - Orders API.json
> +                "description": "Lists all details from an order, through the perspective of the customer who placed the order. \r\n\r\n> You can only access information from orders created in the las
Ok, permissões adicionadas.

2023-12-22 12:55 UTC, Isabella-Veloso commented on VTEX - Orders API.json
> +                "description": "Retrieves a list of orders according to the filters described below. \r\n\r\nThe limit of information retrieval is 30 pages, the default number of orders per page is 1
Ok, permissões adicionadas.

2023-12-22 15:09 UTC, karenkrieger approved these changes
LGTM

2023-12-22 16:03 UTC, merged