EDU-10329 23 h2 kr5 catalog api (part 5)
vtex/openapi-schemas pull request #1106
Opened 2023-12-22 21:17 UTC by karenkrieger

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-12-22 21:53 UTC, julia-rabello requested changes
Além dos comentários e sugestões sinalizadas, verificar os seguintes pontos:

- linha 293 -   remover \r\n do final da description
- linha 1487 - remover \r\n do final da description
- linha 560 - remover \r\n do final da description
- linha 1297 - adicionar exemplo fora do schema
- linha 1487 - remover \r\n do final da description
- linha 1541 - "value" property must match exactly one schema in oneOf
- linha 1559 - "value" property must match exactly one schema in oneOf
- Verificar os checks das linhas 1577 e 1578 "must be string"
- linha 1683 - remover \r\n do final da description
- linha 1681 - adicionar description
- Linha 2099 Adicionar ponto final
- linha 2364 - adicionar example
- Verificar o check da linha 2697 "must be array"
- linha 2986 - terminar description com ponto final. vale dar um ctrl + F por "Videos URLs" para ver se está sem ponto em mais algum lugar
- linha 3195 - adicionar example
- Linha 3855 Adicionar ponto final
- linha 4180 - Type precisa ter um dos valores permitidos
- linha 4211 - enum values precisam ser string
- linha 4272 - exemplo precisa ser integer
- 6248 - adicionar exemplo
- linha 6302 - adicionar exemplo fora do schema
- linha 6479 - adicionar exemplo
- linha 6526 - adicionar exemplo
- linha 6639 - adicionar exemplo

2023-12-22 21:53 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                "summary": "Get specification field value by specification field value ID",
Achei meio longo e repetitivo para um summary. Por mim "Get specification field value" é suficiente, explicando que é por ID na description.

2023-12-22 21:53 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                "description": "Updates a specification field in a category. \r\n>⚠️ This is a legacy endpoint. We recommend using [Update specification](https://developers.vtex.com/vtex-rest-api/ref
Atualizar link para o endpoint citado

2023-12-22 21:53 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                "description": "Retrieves details from a specification field's value by this value's ID. \r\n>⚠️ This is a legacy endpoint. We recommend using [Get specification value](https://develo
Atualizar link para o endpoint citado

2023-12-22 21:53 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                "description": "Creates a specification field in a category. \r\n>⚠️ This is a legacy endpoint. We recommend using [Create specification](https://developers.vtex.com/vtex-rest-api/ref
Atualizar link para o endpoint citado

2023-12-22 21:53 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                "description": "Retrieves details from a specification field by this field's ID. \r\n>⚠️ This is a legacy endpoint. We recommend using [Get specification](https://developers.vtex.com/
Atualizar link para o endpoint citado - https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/specification/-specificationId-

2023-12-22 21:53 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                                            "example": 1,
Tirar `example` repetido de todos os campos desse schema, pois já estão no example geral

2023-12-22 21:53 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                                            "description": "Specification value ID. Mandatory for `FieldTypeId` `5`, `6` and `7`. Must not be used for any other Field types"
```suggestion
                                            "description": "Specification value ID. Mandatory for `FieldTypeId` `5`, `6` and `7`. Must not be used for any other Field types."
```

2024-01-05 18:21 UTC, brunoamui approved these changes
LGTM

2024-01-05 18:40 UTC, julia-rabello approved these changes

2024-01-05 18:41 UTC, merged