New endpoint 3.1 Update additional data (optional)
vtex/openapi-schemas pull request #1127
Opened 2024-01-22 17:31 UTC by ricardoaerobr

#### Types of changes
- [X] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to publish a new endpoint "3.1 Update additional data (optional) - Payments Gateway API (EDU-11419).

2024-02-05 21:03 UTC, PedroAntunesCosta requested changes
Please check spectral error on line 2658. From what I understand, this is an example, so this alert severity maybe doesn't apply. However, it is not desirable to have empty fields in examples either.

2024-02-05 21:38 UTC, ricardoaerobr commented on VTEX - Payments Gateway API.json
> +                        "description": "OK. This endpoint does not return any data in the response body."
Oi, Pedro. Sobre essa questão, nós tinhamos conversado em uma thread do KR5. Mas se julgar pertinente, podemos modificar este entendimento.
https://vtex.slack.com/archives/C05G6ANSU67/p1700247442406849?thread_ts=1700245355.794799&cid=C05G6ANSU67

Aqui um exemplo de como ele renderiza:
![image](https://github.com/vtex/openapi-schemas/assets/87548049/309eb8c7-166b-46c8-baec-cd0ad11587ab)

2024-02-05 21:44 UTC, ricardoaerobr commented on VTEX - Payments Gateway API.json
> +                    "required": true
Sobre este "required": true, acabei verificando que ele está presente em todos os "requestBody" dos endpoints. Seria o caso de remover de todos?

2024-02-05 21:49 UTC, ricardoaerobr commented on VTEX - Payments Gateway API.json
> +                                            "description": "Dataset values."
Neste caso é escaped JSON mesmo. Vou anexar uma ilustração de um exemplo encaminhado por payments.

Talvez modificar o "description" para:  "Dataset values. This information must be sent in escaped JSON format." ?

![image](https://github.com/vtex/openapi-schemas/assets/87548049/7704eead-0e47-4de7-8286-5ad63c7cfa5b)

2024-02-05 21:49 UTC, ricardoaerobr commented on VTEX - Payments Gateway API.json
> +                                            "description": "Dataset values."
Neste caso é escaped JSON mesmo. Vou anexar uma ilustração de um exemplo encaminhado por payments.

Talvez modificar o "description" para:  "Dataset values. This information must be sent in escaped JSON format." ?

![image](https://github.com/vtex/openapi-schemas/assets/87548049/7704eead-0e47-4de7-8286-5ad63c7cfa5b)

2024-02-05 21:50 UTC, ricardoaerobr commented on VTEX - Payments Gateway API.json
> +                                            "description": "Dataset values."
Também tivemos este outro feedback mostrando o formato:

![image](https://github.com/vtex/openapi-schemas/assets/87548049/847a642a-a819-44aa-8e64-0f98529345c9)

2024-02-05 21:52 UTC, ricardoaerobr commented on VTEX - Payments Gateway API.json
> +                                            "description": "Dataset values."
Sobre a linha 2658, este response sempre vem com o "description" : "" , então infelizmente não poderia preenche-lo ou deixá-lo "null".

2024-02-06 14:57 UTC, PedroAntunesCosta commented on VTEX - Payments Gateway API.json
> +                    "required": true
Melhor remover todos sim. Olhei aqui alguns endpoints da API de catálogo e do VTEX ID e elas não tem esse campo. Também não vejo sentido conceitual.

2024-02-06 15:25 UTC, PedroAntunesCosta approved these changes
Great!

2024-02-06 15:25 UTC, merged