Feat-pick-and-pack-api
vtex/openapi-schemas pull request #1177
Opened 2024-04-08 15:52 UTC by karenkrieger

#### Types of changes
- [X] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2024-04-12 20:36 UTC, crisak commented
@karenkrieger  Suggestions for improvements to Postman documentation.
<img width="1383" alt="unused variable" src="https://github.com/vtex/openapi-schemas/assets/41553975/09934de0-1d81-4f03-bbcd-603a22c6c263">
![variable not defined](https://github.com/vtex/openapi-schemas/assets/41553975/245d9c24-c58f-4a80-b58c-8c0fe30d222b)

![reference variable](https://github.com/vtex/openapi-schemas/assets/41553975/8b268669-5308-49a9-b9a4-54e141bbc07a)
<img width="1406" alt="Reference variable 02" src="https://github.com/vtex/openapi-schemas/assets/41553975/5572be6f-0871-4223-a516-f27f12004cdd">
<img width="1343" alt="Reference variables 03" src="https://github.com/vtex/openapi-schemas/assets/41553975/4c9c8001-dde9-4c50-928e-f77f1f60688e">

2024-04-16 14:32 UTC, Isabella-Veloso requested changes
Request changes

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Se for o caso, colocar o formato. Exemplo: "Currency code in [ISO 4217](https://www.iban.com/currency-codes) format."

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
```suggestion
                        "description": "Insurance cost in cents."

```

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Ver comentário anterior sobre currency code.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Evitar descrições vazias.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Evitar descriptions vazias.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Adicionar formato.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Adicionar formato.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Adicionar formato.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
```suggestion
                        "description": "Defines if the carrier is international (`true`) or not (`false`).
Carrier international."

```

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
```suggestion
                        "description": "Shipping cost in cents."

```

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Ver descrição de
```suggestion
                        "description": "Cost currency code in [ISO 4217](https://www.iban.com/currency-codes) format."

```

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
In kilometers?

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
```suggestion
                        "description": "Delivery shipping price."
```suggestion
                        "description": "Delivery shipping price in cents."

```
```

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Add format.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Se possível, adicionar exemplos para campos null.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
In kilometers?

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
```suggestion
                        "description": "Agent phone number."

```

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
No exemplo tem um `+` antes do número, valeria mencionar isso aqui.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Preferivelmente em inglês.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Preferivelmente em inglês.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
Preferivelmente em inglês.

2024-04-16 14:32 UTC, Isabella-Veloso commented on VTEX - Pick and Pack Protocol API.json
> +
```suggestion
            "description": "These endpoints must be developed to integrate with the Lastmile Pick and Pack Protocol API."

```

2024-04-24 20:44 UTC, Isabella-Veloso approved these changes
LGTM

2024-04-25 16:21 UTC, merged