Update VTEX - Orders API.json
vtex/openapi-schemas pull request #372
Opened 2021-05-13 19:07 UTC by PedroAntunesCosta

Orders API
Order Invoice Notification endpoint

Inclusion of the field `embeddedInvoice`, which receives the XML of the invoice

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

2021-05-26 17:07 UTC, karenkrieger requested changes

2021-05-26 17:07 UTC, karenkrieger commented on VTEX - Orders API.json
> +                        "description": "XML of the invoice."
Adicionar um `default` com um valor exemplo para o usuário.

2021-05-27 18:08 UTC, PedroAntunesCosta commented
Acho que um exemplo seria muito grande para o `default`. Mas pensei em colocar no markdown da página separado e indicar no `description` que atualizei agora. O que acha?

2021-05-27 19:07 UTC, karenkrieger approved these changes

2021-05-27 19:07 UTC, merged