Checkout API - Order placement endpoints
vtex/openapi-schemas pull request #394
Opened 2021-06-24 22:39 UTC by PedroAntunesCosta

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

Inserting 2 new endpoints:
`/api/checkout/pub/orderForm/{orderFormId}/transaction`
`/api/fulfillment/pvt/orders`

Inserting the new `allowOutdatedData` parameter to the `/api/checkout/pub/orderForm/{orderFormId}/items` endpoint.

2021-06-25 19:41 UTC, karenkrieger requested changes

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +              "example": ["shippingData", "paymentData"]
Tem que colocar como `default`, senão ele não vai exibir o exemplo na documentação

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +        "tags": ["Order placement"],
É com `[ ]` mesmo? Isso vai renderizar nas tags do ReadMe

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                "title": "Request body",
Colocar `title` como `""`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                    "example": "41a22925298a4ddca95318131a25b000"
Trocar `example` por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                    "example": false
Trocar `example` por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                    "example": false
Trocar `example` por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                    "example": 6800
Trocar `example` por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                    "example": 6800
Trocar `example` por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                    "example": 0
Trocar `example` por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +        "tags": ["Order placement"],
É com `[ ]` mesmo? Isso vai renderizar nas tags do ReadMe

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                "example": false
Se você colocar `example` no `boolean` ele não seleciona nada, se quiser colocar o `false` tem que substituir por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                          "example": false
Se você colocar `example` no `boolean` ele não seleciona nada, se quiser colocar o `false` tem que substituir por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "properties": {}
Acho que não faz sentido manter um `properties` sem nada. Também adicionaria um exemplo aqui

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                  "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                  "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                  "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                  "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "example": ""
Adicionar exemplo

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "example": false
Se você colocar `example` no `boolean` ele não seleciona nada, se quiser colocar o `false` tem que substituir por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "example": false
Se você colocar `example` no `boolean` ele não seleciona nada, se quiser colocar o `false` tem que substituir por `default`

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                        "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                          "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "example": ""
Adicionar exemplo

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "description": "",
Adicionar descrição

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "example": ""
Adicionar exemplo

2021-06-25 19:41 UTC, karenkrieger commented on VTEX - Checkout API.json
> +              "examples": {
Esse `example` parece perdido

2021-06-28 22:36 UTC, PedroAntunesCosta commented on VTEX - Checkout API.json
> +        "tags": ["Order placement"],
Eu copiei de endpoints que já existiam. Inclusive já vi em algum arquivo listas com mais de uma tag nesse campo. :thonking:

2021-06-28 22:39 UTC, PedroAntunesCosta commented on VTEX - Checkout API.json
> +                    "example": "41a22925298a4ddca95318131a25b000"
Por que `default` nesse caso?

2021-06-28 23:11 UTC, PedroAntunesCosta commented on VTEX - Checkout API.json
> +                          "description": "",
Excluí a linha 4203. Entendo que os itens do array estão contemplados na descrição do array.Essa linha deve ter ficado aí como vestígio de algum modelo que copiei.

2021-06-30 17:31 UTC, karenkrieger requested changes
Falta só um comentário pra ser resolvido e depois podemos aprovar!

2021-06-30 17:31 UTC, karenkrieger commented on VTEX - Checkout API.json
> +        "tags": ["Order placement"],
Fair enough

2021-06-30 17:31 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                    "example": "41a22925298a4ddca95318131a25b000"
Dentro do request body é bom adicionar o `default`, porque é ele que renderiza o exemplo naquele formulário que tem no ReadMe

2021-06-30 19:54 UTC, karenkrieger approved these changes
LGTM

2021-06-30 19:54 UTC, merged