Edu 4587 stock keeping unit by sales channel route
vtex/openapi-schemas pull request #431
Opened 2021-09-20 22:06 UTC by karenkrieger

#### Types of changes
- [X] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

New query param

2021-09-21 13:01 UTC, vilmabezerra commented on VTEX - Catalog API.json
> +                        "description": "If set as `true`, it allows user to decide if the SKUs that are not assigned to a specific trade policy should be also returned",
Actually, if set as `false` the SKUs not assigned to a specific trade policy should be also returned.

2021-09-21 13:01 UTC, vilmabezerra commented on VTEX - Catalog API.json
> +                            "default": false
the default behaviour is set as `true`

2021-09-21 13:02 UTC, vilmabezerra requested changes
Hey, it looks awesome, thanks! 
Only a specific detail, that I wasn't clear about it before, that needs to be changed.

2021-09-28 18:40 UTC, brunoamui approved these changes
LGTM

2021-09-28 18:40 UTC, merged