Checkout get client new 22092021
vtex/openapi-schemas pull request #432
Opened 2021-09-23 21:33 UTC by PedroAntunesCosta

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

#### New endpoint
Get client profile by email

2021-09-24 17:35 UTC, karenkrieger requested changes

2021-09-24 17:35 UTC, karenkrieger commented on VTEX - Checkout API.json
> +              "type": "string"
Adicionar `default`

2021-09-24 17:35 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "type": "string"
Adicionar `description`

2021-09-27 15:02 UTC, PedroAntunesCosta commented on VTEX - Checkout API.json
> +                              "type": "string"
Acho que não chegamos a discutir isso, mas não sei se acho que devemos ter `description` de itens escalares de array. Tipo, em tese, tá contemplado na própria `description` do array.

O que acha?

2021-09-27 17:07 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                              "type": "string"
Acho que em alguns casos vale colocar uma descrição, mas nesse em específico concordo contigo que a descrição do array já é o suficiente

2021-09-27 17:08 UTC, karenkrieger approved these changes
LGTM

2021-09-27 17:08 UTC, merged