Feedbacks 01102021
vtex/openapi-schemas pull request #434
Opened 2021-10-01 22:48 UTC by PedroAntunesCosta

### Solving feedbacks
Details in each commit

#### Readme previews
[Orders](https://github.com/vtex/openapi-schemas/blob/feedbacks-01102021/VTEX%20-%20Orders%20API.json)
[Checkout](https://github.com/vtex/openapi-schemas/blob/feedbacks-01102021/VTEX%20-%20Checkout%20API.json)
[Logistics](https://preview.readme.io/get_logistics-pvt-shipping-policies-id?url=https%3A%2F%2Fraw.githubusercontent.com%2Fvtex%2Fopenapi-schemas%2Ffeedbacks-01102021%2FVTEX+-+Logistics+API.json)

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

2021-10-04 15:16 UTC, karenkrieger requested changes

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Orders API.json
>                          "schema": {
Adicionar `default`

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                        "description": "Settings for the Scheduled Delivery feature.",
Se você tem o default das propriedades, você tem o default do objeto

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                "default": {},
Mesma coisa que o comentário anterior

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                        "title": "dayOfWeek",
Adicionar descrição

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                                "description": "",
Adicionar descrição

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                                "description": "",
Adicionar descrição

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                                "description": "",
Adicionar descrição

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                                "default": null,
Melhor um default como `{}` do que `null`, não?

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                                        "description": "Defines how the delivery capacity is measured for this reservation window, by maximum number of orders (`\"ORDE
Adicionar `default`

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                        "description": "",
Adicionar descrição

2021-10-04 15:16 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                    "type": "array",
Coloca o `"title"= ""` pra não ficar com o título feio

2021-10-05 13:29 UTC, PedroAntunesCosta commented on VTEX - Logistics API.json
> +                                    "type": "array",
Onde fica esse `"title": ""`? No `schema`? Acho que não tá na checklist.

E onde fica isso no readme? As respostas não são agrupadas pelo status + description?

2021-10-05 13:46 UTC, PedroAntunesCosta commented on VTEX - Logistics API.json
> +                                                                "default": null,
Não sei :thonking:. Na real o default desse campo é, de fato, `null` e as propriedades já tem os respectivos defaults que o readme vai mostrar pro leitor.

Como não tem impacto na renderização, sugiro uma dessas 2 opções:
a) Deixa porque fica mais correto
b) Tiramos o default pra priorizar o default das propriedades

2021-10-05 16:28 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                    "type": "array",
Sim, fica no `schema` mesmo. Esse título aparece logo acima do body, seja o response ou request.

2021-10-05 16:29 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                                "default": null,
Acho que eu iria pelo `A` só porque se a gente mudar de plataforma o render não necessariamente vai seguir as regras do readme.

2021-10-05 17:32 UTC, karenkrieger approved these changes
LGTM

2021-10-05 17:32 UTC, merged