Add body parameters create giftcard
vtex/openapi-schemas pull request #455
Opened 2021-11-08 14:14 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

2021-11-08 17:25 UTC, karenkrieger requested changes
Precisamos smepre adicionar as `description`s dos campo (tanto request quanto response bodies) para que a pessoa saiba o que ele aquele campo representa.

2021-11-08 17:25 UTC, karenkrieger commented on VTEX - Giftcard API.json
> +              "type": "string",
Adicionar `description` do campo

2021-11-08 17:25 UTC, karenkrieger commented on VTEX - Giftcard API.json
>                "default": "email@email.com.br"
Adicionar `description` do campo

2021-11-08 17:25 UTC, karenkrieger commented on VTEX - Giftcard API.json
> +                "default": false
Adicionar `description` do campo

2021-11-08 17:25 UTC, karenkrieger commented on VTEX - Giftcard API.json
> +                "default": false
Adicionar `description` do campo

2021-11-08 17:25 UTC, karenkrieger commented on VTEX - Giftcard API.json
> +                "default": false
Adicionar `description` do campo

2021-11-09 11:42 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
>                "default": "email@email.com.br"
Adicionado.

2021-11-09 11:42 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                "default": false
Adicionado.

2021-11-09 11:42 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                "default": false
Adicionado.

2021-11-09 11:42 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                "default": false
Adicionado.

2021-11-09 12:22 UTC, karenkrieger approved these changes
LGTM

2021-11-09 12:22 UTC, merged