Edu 5222 adicionar response bodies na api de promotion taxes Tag de Coupons
vtex/openapi-schemas pull request #461
Opened 2021-11-10 21:56 UTC by karenkrieger

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

Adicionei response body em todos os endpoints da tag de `Coupons`

2021-11-11 23:30 UTC, PedroAntunesCosta requested changes

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                        "content": {
Não vou bloquear merge, mas sugiro ajustar a indentação nesse trecho.

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "description": "Insert a flag with the promotion name used in the product's window display and page."
Não vou bloquear merge, mas não entendi essa descrição. É desse campo mesmo? 😬

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "description": "Define which days of the week the promotion will applied."
Inserir `items` do array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                        "maxPricesPerItems": {
Inserir `items` e `description` do array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                        },
incluir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` e description` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "items": {}
inserir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "items": {}
inserir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
Schema não condiz com `type`. Alinhar `type`, `description` e schema

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
Schema não condiz com `type`. Alinhar `type`, `description` e schema

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` e description` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` e description` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                        "collections": {
Schema não condiz com `type`. Alinhar `type`, `description` e schema

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "items": {}
inserir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                        "cardIssuers": {
inserir `items` e description` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` e description` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                        },
inserir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` e description` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                        },
inserir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
inserir `items` e description` no array

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "items": {}
inserir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "description": ""
incluir `description`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "description": ""
incluir `description`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                            "items": {}
inserir `type` no `items`

2021-11-11 23:30 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                        "default":""
inserir valor para `default`

2021-11-12 18:23 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
Esse campo tá deprecado, então nem é pra ser utilizado

2021-11-12 18:23 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
Esse campo tá deprecado, então nem é pra ser utilizado

2021-11-12 18:23 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> +                                        "cardIssuers": {
Esse campo tá deprecado, então nem é pra ser utilizado

2021-11-12 18:23 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
Esse campo tá deprecado, então nem é pra ser utilizado

2021-11-12 18:23 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
Esse campo tá deprecado, então nem é pra ser utilizado

2021-11-12 18:23 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> +                                            "type": "array",
Esse campo tá deprecado, então nem é pra ser utilizado

2021-11-12 20:09 UTC, PedroAntunesCosta approved these changes
LGTM

2021-11-12 20:09 UTC, merged