Get offers
vtex/openapi-schemas pull request #468
Opened 2021-11-24 22:44 UTC by jumeyermattosarruda

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

New Get Offers List endpoint, following the doc request described in [EDU-4474](https://vtex-dev.atlassian.net/browse/EDU-4474).

2021-11-29 22:33 UTC, karenkrieger requested changes

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
```suggestion
                        "description": "OK",
```

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar schema da response

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                                "default": ""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                                "default": ""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                                "default": "",
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "default": ""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                    "default":""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                    "default":""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                    "description": ""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "default":""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "default":""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "default":""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "default":""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "default":""
Adicionar default

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionar description

2021-11-29 22:33 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": ""
Adicionar description

2021-11-30 17:02 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionado!

2021-11-30 17:21 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionado!

2021-11-30 17:21 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionado!

2021-11-30 17:21 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "default":""
Adicionado!

2021-11-30 17:22 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": ""
Adicionado!

2021-11-30 17:23 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "",
Adicionado!

2021-11-30 17:23 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:24 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:24 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:25 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:26 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:26 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:27 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:27 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:31 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:34 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                            "type": "string"
Adicionado!

2021-11-30 17:34 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                            "type": "string"
Adicionado!

2021-11-30 17:35 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:36 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:42 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:42 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-11-30 17:43 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:03 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:03 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:03 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:04 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:05 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:05 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:06 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:08 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:09 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:09 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:10 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:11 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:12 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:13 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
Vou adicionar os schemas dos outros responses em outro PR

2021-12-02 22:14 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
Added!

2021-12-02 22:17 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
Added!

2021-12-02 22:17 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
Added!

2021-12-02 22:17 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:18 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +
(Acho que esses comentários tão se repetindo)

2021-12-02 22:19 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                                "default": ""
Added!

2021-12-02 22:23 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                                "default": ""
Added!

2021-12-02 22:23 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                                "default": "",
Added!

2021-12-02 22:29 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Deletei esse schema, não é mais usado em nenhuma chamada

2021-12-02 22:29 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Added!

2021-12-02 22:32 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Added!

2021-12-02 22:32 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Vou investigar mais em outro PR

2021-12-02 22:33 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                        "default": ""
Vou investigar mais em outro PR

2021-12-02 22:34 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Added!

2021-12-02 22:35 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                    "default":""
Added!

2021-12-02 22:35 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Added!

2021-12-02 22:35 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                    "default":""
Added

2021-12-02 22:35 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Added

2021-12-02 22:36 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                    "description": "",
Added!

2021-12-02 22:36 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                    "description": ""
Added!

2021-12-02 22:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "default":""
Added!

2021-12-02 22:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "",
Added!

2021-12-02 22:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "default":""
Added

2021-12-02 22:38 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "default":""
Added!

2021-12-02 22:38 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "",
Added!

2021-12-02 22:38 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "",
Added!

2021-12-02 22:38 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "",
Added!

2021-12-02 22:38 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "default":""
Added!

2021-12-03 19:43 UTC, karenkrieger approved these changes
LGTM

2021-12-03 19:45 UTC, merged