Edu 5350 update catalog api reference
vtex/openapi-schemas pull request #471
Opened 2021-12-02 19:21 UTC by karenkrieger

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

Atualizações segundo o documento [VTEX Catalog Architecture](https://docs.google.com/document/d/1pEVX4UXNQ1ARrmTuC0dAFBoiGIukAScbN5PXIq7mc94/)

2021-12-03 13:48 UTC, brunoamui reviewed
Ele ta reclamando mto de uns casos onde o schema especifica u tipo, mas no exemplo tem "null". Se realmente a plataforma puder responder null em alguns casos, temos que alterar o schema da resposta usando esse exemplo aqui: Acho que para todos esses casos, da pra usar a solução sugerida aqui: https://stackoverflow.com/questions/16241333/specify-a-value-can-be-a-string-or-null-with-json-schema

2021-12-03 19:07 UTC, PedroAntunesCosta requested changes

2021-12-03 22:39 UTC, htadashi commented
> Ele ta reclamando mto de uns casos onde o schema especifica u tipo, mas no exemplo tem "null". Se realmente a plataforma puder responder null em alguns casos, temos que alterar o schema da resposta usando esse exemplo aqui: https://stackoverflow.com/questions/16241333/specify-a-value-can-be-a-string-or-null-with-json-schema

@brunoamui Tive um problema similar com a API da LM (muitas das respostas retornam parâmetros com null). Para resolver, usei o campo [`nullable : true`](https://swagger.io/docs/specification/data-models/data-types/#:~:text=OpenAPI%203.0%20does%20not%20have%20an%20explicit%20null%20type%20as%20in%20JSON%20Schema%2C%20but%20you%20can%20use%20nullable%3A%20true%20to%20specify%20that%20the%20value%20may%20be%20null.%20Note%20that%20null%20is%20different%20from%20an%20empty%20string%20%22%22.). Parece que o OpenAPI não tem o tipo `null`

2021-12-08 15:08 UTC, PedroAntunesCosta submitted a review, later dismissed
LGTM

2021-12-08 16:04 UTC, merged