Update VTEX - Promotions & Taxes API.json
vtex/openapi-schemas pull request #479
Opened 2022-01-18 17:57 UTC by karenkrieger

Correção do exemplo e do nome da variável

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

2022-01-18 21:33 UTC, PedroAntunesCosta requested changes

2022-01-18 21:33 UTC, PedroAntunesCosta commented on VTEX - Promotions & Taxes API.json
> +                                "description": "sadfgthju~´pç",
Achei estranha essa `description`. Dá uma conferida?

2022-01-19 14:07 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> +                                "description": "sadfgthju~´pç",
Tá bizarra mesmo

2022-01-19 20:49 UTC, PedroAntunesCosta approved these changes
LGTM

2022-01-21 13:44 UTC, merged