Update VTEX - Marketplace Protocol.json
vtex/openapi-schemas pull request #495
Opened 2022-02-09 14:54 UTC by Isabella-Veloso

The "properties" object is not an array; and the "allowsRemapParent" property doesn't exist.

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

Accordingly to the product team, the "properties" object is not an array. And the "allowsRemapParent" property doesn't exist.

2022-02-09 19:48 UTC, karenkrieger requested changes

2022-02-09 19:48 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
>                          "description": "",
Adicionar descrição

2022-02-11 14:16 UTC, Isabella-Veloso commented on VTEX - Marketplace Protocol.json
>                          "description": "",
Descrição adicionada.

2022-02-11 14:35 UTC, karenkrieger approved these changes
LGTM

2022-02-11 14:37 UTC, merged