Mentoria 16 feb
vtex/openapi-schemas pull request #499
Opened 2022-02-16 15:54 UTC by jumeyermattosarruda

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

Added a hyperlink to a logistics endpoint for educational reasons, in a mentoring session with Jessica and Gustavo.

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

No need to create a release note, since it's just a hyperlink for teaching purposes.

2022-02-16 17:13 UTC, karenkrieger requested changes

2022-02-16 17:13 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                "description": "This endpoint lists existing [shipping policies](https://help.vtex.com/en/tutorial/politica-de-envio--tutorials_140) from carriers in your store, searching by their ID
Coloca a slug do artigo em EN também pra não termos problemas com o redirecionamento

2022-02-17 19:15 UTC, jumeyermattosarruda commented on VTEX - Logistics API.json
> +                "description": "This endpoint lists existing [shipping policies](https://help.vtex.com/en/tutorial/politica-de-envio--tutorials_140) from carriers in your store, searching by their ID
Feito!

2022-02-17 19:44 UTC, karenkrieger approved these changes
LGTM

2022-02-17 21:26 UTC, merged