Replace capture for settlement
vtex/openapi-schemas pull request #519
Opened 2022-03-30 13:33 UTC by henriquessb

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

Replaced all occurrences of the term "capture" for "settlement" in the [PPP API](https://developers.vtex.com/vtex-rest-api/reference/payment-provider-protocol-api-overview).

2022-03-30 15:05 UTC, karenkrieger requested changes
Henrique, pode só arrumar os alertas vermelhos do Spectral? De resto tá tudo ✅

2022-03-30 19:11 UTC, henriquessb commented
@karenkrieger Fiz as mudanças pedidas pelo Spectral. As mudanças foram meio grandes, mas consegui corrigir tudo. Agora está tudo ✅ para fazer o merge?

2022-03-31 15:49 UTC, karenkrieger requested changes

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                                    "type": "string"
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                                    "type": "string"
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                        "type": "array",
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                        "type": "array",
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                                    "type": "string"
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                                    "type": "string"
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                                    "type": "array",
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                                                "type": "string"
Adicionar descrição

2022-03-31 15:49 UTC, karenkrieger commented on VTEX - Payment Provider Protocol.json
> +                                                "type": "string"
Adicionar descrição

2022-04-01 18:09 UTC, karenkrieger approved these changes
LGTM

2022-04-04 14:21 UTC, merged