Sent offers integration guide
vtex/openapi-schemas pull request #542
Opened 2022-05-11 21:17 UTC by Isabella-Veloso

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

Sent Offers APIs were documented in Openapi-schemas-internal and must be published as public link now.

2022-05-12 18:31 UTC, karenkrieger requested changes

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar `schema`

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand ",
```suggestion
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
```

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand ",
```suggestion
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
```

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Adicionar descrição

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand ",
```suggestion
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
```

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Adicionar descrição

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Adicionar descrição

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Adicionar descrição

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar `schema`

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "Describes the type of the content being sent",
```suggestion
                        "description": "Describes the type of the content being sent.",
```

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand ",
```suggestion
                        "description": "HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.",
```

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                            "default": ""
Adicionar default

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": "",
```suggestion
                        "description": "OK",
```

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "headers": {}
Adicionar `schema`

2022-05-12 18:31 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Adicionar descrição

2022-05-13 21:25 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Descrição adicionada.

2022-05-13 21:25 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Descrição adicionada.

2022-05-13 21:25 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Descrição adicionada.

2022-05-13 21:26 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Descrição adicionada.

2022-05-13 21:26 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Descrição adicionada.

2022-05-13 21:26 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Descrição adicionada.

2022-05-13 21:26 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": "",
Descrição adicionada.

2022-05-13 21:27 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                            "default": ""
Default adicionado.

2022-05-13 21:27 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "description": ""
Descrição adicionada.

2022-05-13 21:27 UTC, Isabella-Veloso commented on VTEX - Marketplace APIs.json
> +                        "type": "string"
Descrição adicionada.

2022-05-19 19:19 UTC, karenkrieger approved these changes
LGTM

2022-05-19 19:21 UTC, merged