Edu 6637 taxes endpoints for promotions & taxes api
vtex/openapi-schemas pull request #548
Opened 2022-05-17 13:03 UTC by julia-rabello

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [x] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2022-05-18 22:41 UTC, karenkrieger requested changes

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
Definir `items`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`default`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
Adicionar `schema`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-18 22:41 UTC, karenkrieger commented on VTEX - Promotions & Taxes API.json
> -
`.`

2022-05-20 20:32 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                    "title": "",
@karenkrieger não entendi essa, o schema tá declarado logo depois

2022-05-20 20:40 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                        "headers": {}
Essa response é vazia

2022-05-20 21:31 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Prices Legacy v1

2022-05-20 21:31 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Prices Legacy v1

2022-05-20 21:32 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:32 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:32 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:32 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:33 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Prices Legacy v1

2022-05-20 21:33 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                            "validFrom": {
Prices Legacy v1

2022-05-20 21:33 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Prices Legacy v1

2022-05-20 21:33 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:33 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:33 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:34 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "format": "int32"
Prices Legacy v1

2022-05-20 21:36 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Unused schema. Excluído.

2022-05-20 21:37 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Prices Legacy v1

2022-05-20 21:38 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Unused schema

2022-05-20 21:40 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "nullable": true
Unused schema

2022-05-20 21:40 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Unused schema

2022-05-20 21:40 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "boolean"
Unused schema

2022-05-20 21:41 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +                                "type": "string"
Unused schema

2022-05-20 21:42 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> +
Acho que a resposta é só OK mesmo

2022-05-20 21:43 UTC, julia-rabello commented on VTEX - Promotions & Taxes API.json
> -
Acho que a resposta é só OK

2022-05-23 20:12 UTC, karenkrieger approved these changes
LGTM

2022-05-23 20:25 UTC, karenkrieger approved these changes
LGTM

2022-05-23 20:26 UTC, merged