Edu 6827 sent offers
vtex/openapi-schemas pull request #567
Opened 2022-06-09 15:43 UTC by Isabella-Veloso

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

Added a new method to an endpoint.

2022-06-09 17:01 UTC, jumeyermattosarruda reviewed
Revisado!

2022-06-09 17:01 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                                      "description": "Name of the marketplace the feed is about."
E acho que 

> "Name of the marketplace the feed is about."

não é tão preciso gramaticalmente. Talvez:
Name of the marketplace, or channel, present in the feed.
Já que o feed não é só sobre um marketplace necessariamente, mas o marketplace é um objeto dentro do feed.

2022-06-09 17:01 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                                      "description": "Graphic symbol that identifies the marketplace."
URL redirecting to the image file of the graphic symbol that identifies the marketplace*

2022-06-10 15:46 UTC, karenkrieger requested changes

2022-06-10 15:46 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "In [Sent Offers](https://help.vtex.com/en/tutorial/offers-listing--7MRb9S78aBdZjFGpbuffpE), a feed is a list of information about seller's offers sent to a marketplace
```suggestion
                "description": "In [Sent Offers](https://help.vtex.com/en/tutorial/offers-listing--7MRb9S78aBdZjFGpbuffpE), a feed is a list of information about seller's offers sent to a marketplace, and it is updated in real-time with content provided by the marketplace and VTEX modules. \n\nSince a seller can have integrations with multiple marketplaces, numerous feeds can be associated with an account. This endpoint retrieves a list with all the feeds related to an account.\n\nThe feature is available for integrations with [Mercado Libre Classic](https://help.vtex.com/pt/tracks/configurar-integracao-do-mercado-livre--2YfvI3Jxe0CGIKoWIGQEIq), [Mercado Libre Premium](https://help.vtex.com/pt/tracks/configurar-integracao-do-mercado-livre--2YfvI3Jxe0CGIKoWIGQEIq/51oWBHvVxSs8eAwLQhSbSd), [Netshoes](https://help.vtex.com/pt/tracks/configurar-integracao-da-netshoes--5Ua87lhFg4m0kEcuyqmcCm), and VTEX marketplaces. For more information, check out the [Sent Offers Integration Guide](https://developers.vtex.com/vtex-rest-api/docs/sent-offers-integration-guide-connectors).",
```

2022-06-10 15:46 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                                      "description": "Sales channel (or [trade policy](https://help.vtex.com/en/tutorial/como-funciona-uma-politica-comercial--6Xef8PZiFm40kg2STrMkMV#master-data)) use
```suggestion
                                      "description": "Sales channel (or [trade policy](https://help.vtex.com/en/tutorial/how-trade-policies-work--6Xef8PZiFm40kg2STrMkMV#master-data)) used in the integration."
```

2022-06-10 15:57 UTC, karenkrieger approved these changes
LGTM

2022-06-10 15:58 UTC, merged