Partial invoices
vtex/openapi-schemas pull request #575
Opened 2022-06-21 22:15 UTC by jumeyermattosarruda

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

We have updated the architecture of how our OMS communicates with VTEX's Payment gateway so that partial invoices also trigger partial settlements in transactions. The following endpoints had their descriptions changed, to fit the new model:

[Register Change on Order](https://developers.vtex.com/vtex-rest-api/reference/registerchange)
[Invoice notification](https://developers.vtex.com/vtex-rest-api/reference/invoicenotification)
[Retrieve Payment transaction](https://developers.vtex.com/vtex-rest-api/reference/getpaymenttransaction)
[Update order's partial invoice (send tracking number)](https://developers.vtex.com/vtex-rest-api/reference/updatepartialinvoicesendtrackingnumber)

I also used the same PR to fix minor details on the Orders API, sent in through the following feedbacks:
- [EDU-5383](https://vtex-dev.atlassian.net/browse/EDU-5383)
- [EDU-2120](https://vtex-dev.atlassian.net/browse/EDU-2120)
- [EDU-6693](https://vtex-dev.atlassian.net/browse/EDU-6693)
- [EDU-6722](https://vtex-dev.atlassian.net/browse/EDU-6722)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [x] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2022-06-22 17:07 UTC, karenkrieger commented on VTEX - Orders API.json
> +                        "description": "Status description which is displayed on the Admin panel. This field is obsolete and may not return any value."
Eu colocaria um `deprecated` aqui também pra garantir

2022-06-22 17:07 UTC, karenkrieger commented on VTEX - Orders API.json
> +                        "description": "Status description which is displayed on the Admin panel. This field is obsolete and may not return any value."
Eu colocaria um `deprecated` aqui também pra garantir

2022-06-22 20:00 UTC, jumeyermattosarruda commented on VTEX - Orders API.json
> +                "description": "This request allows [changing an order](https://help.vtex.com/en/tutorial/alteracao-de-itens-de-um-pedido-finalizado--tutorials_190) by:\n\r- Adding items\n\r- Removin
É que tô esperando a tradução ficar pronta, mas vai casar com a data de publicação desse PR

2022-06-22 20:03 UTC, jumeyermattosarruda commented on VTEX - Orders API.json
> +                        "description": "Status description which is displayed on the Admin panel. This field is obsolete and may not return any value."
Added!

2022-06-23 19:35 UTC, jumeyermattosarruda commented
O Spectral ainda aponta erros que já foram corrigidos e commitados. É estranho também que os erros apontados pra mim ao _Re-run all jobs_ são diferentes dos erros que aparecem para a Karen. De qualquer forma, todos os erros já foram corrigidos, o Spectral que não parece captar isso /:

2022-06-24 19:09 UTC, karenkrieger requested changes

2022-06-24 19:09 UTC, karenkrieger commented on VTEX - Orders API.json
> +                "description": "This request allows [changing an order](https://help.vtex.com/en/tutorial/alteracao-de-itens-de-um-pedido-finalizado--tutorials_190) by:\n\r- Adding items\n\r- Removin
```suggestion
                "description": "This request allows [changing an order](https://help.vtex.com/en/tutorial/alteracao-de-itens-de-um-pedido-finalizado--tutorials_190) by:\n\r- Adding items\n\r- Removing items\n\r- Applying discount to the total value of the order\n\r- Incrementing the total value of the order. \n\nIn those scenarios of order changes, it is possible to insert a [Partial invoice](https://help.vtex.com/en/tracks/pedidos--2xkTisx4SXOWXQel8Jg8sa/q9GPspTb9cHlMeAZfdEUe). The total value of the order will be updated after the insertion of the invoice, even when there's a partial invoice scenario. The updated value is settled by VTEX's Payment Gateway. The reimbursement for the shopper is automatic. \n\r\n\rThis action can only be done for orders in these status:\n\r- `handling`\n\r- `waiting-for-fulfillment`. \n\r\n\r> The `Change order` resource is needed to use this API request. This is included in `OMS - Full access` and `IntegrationProfile - Fulfillment Oms`, among other default roles available in the Admin. Learn more about the [License manager roles and resources](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#).",
```

2022-06-24 19:49 UTC, karenkrieger approved these changes
LGTM

2022-06-27 20:20 UTC, merged