Logistics multiple fixes
vtex/openapi-schemas pull request #582
Opened 2022-06-24 20:16 UTC by Isabella-Veloso

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2022-06-24 21:52 UTC, karenkrieger requested changes
Arrumar os erros do Spectral

2022-06-27 21:55 UTC, Isabella-Veloso commented
> Arrumar os erros do Spectral

Feito.

2022-06-27 21:56 UTC, Isabella-Veloso commented
> Arrumar os erros do Spectral

Feito na maior parte.

2022-06-28 17:39 UTC, karenkrieger commented on VTEX - Logistics API.json
> +                                                            "description": "This field returns the dock's processing time in days and hours. If none is configured, the call returns `00:00:00`.",
```suggestion
                                                            "description": "This field returns the dock's processing time in days and hours. If none is configured, the request returns `00:00:00`.",
```

2022-06-28 18:44 UTC, Isabella-Veloso commented on VTEX - Logistics API.json
>                                                  "description": ""
Feito.

2022-06-28 19:39 UTC, karenkrieger approved these changes
LGTM
![](https://media.giphy.com/media/Guccz4Oq87bncsm1j4/giphy.gif)

2022-06-28 19:41 UTC, merged