Add Catalog API response bodies - Category
vtex/openapi-schemas pull request #621
Opened 2022-09-02 14:40 UTC by julia-rabello

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2022-09-06 21:38 UTC, karenkrieger requested changes

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "string"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "number"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "description": "Email of the admin responsible for the seller. ",
Remover o espaço no final

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "description": "Name of the marketplace, used to guide payments. This field should be nulled if the marketplace is responsible for processing payments. Check out our [Split Pa
https://help.vtex.com/en/tutorial/split-payment--6k5JidhYRUxileNolY2VLx

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "description": "Name of the marketplace, used to guide payments. This field should be nulled if the marketplace is responsible for processing payments. Check out our [Split Pa
https://help.vtex.com/en/tutorial/split-payment--6k5JidhYRUxileNolY2VLx

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "string"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "format": "int32"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "format": "int32"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "string"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "format": "int32"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "description": "Specification Group Name"
Adicionar `.`

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "format": "int32"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "format": "int32"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "type": "string"
Adicionar description

2022-09-06 21:38 UTC, karenkrieger commented on VTEX - Catalog API.json
> +                        "format": "int32"
Adicionar description

2022-09-09 12:13 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "string"
Esse schema faz parte do endpoint Get Specifications Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:13 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Get Specifications Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:13 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Get Specifications Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:18 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Esse schema faz parte do endpoint Get Specifications Tree By Category Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:21 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Create Specification Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:21 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "string"
Esse schema faz parte do endpoint Create Specification Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:21 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Create Specification Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:22 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Create Specification Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:23 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Create Specification Group, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:24 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint List Specifications Group by Category, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:25 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Esse schema faz parte do endpoint Get Specifications Values By Field Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:25 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Esse schema faz parte do endpoint Get Specifications Values By Field Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:25 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Esse schema faz parte do endpoint Get Specifications Tree By Category Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:26 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Get Specifications Tree By Category Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:26 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "string"
Esse schema faz parte do endpoint Get Specifications Tree By Category Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:29 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "boolean"
Esse schema faz parte do endpoint Get Specifications Values By Field Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:30 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "format": "int32"
Esse schema faz parte do endpoint Get Specifications Values By Field Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 12:30 UTC, julia-rabello commented on VTEX - Catalog API.json
> +                        "type": "string"
Esse schema faz parte do endpoint Get Specifications Values By Field Id, que não foi revisado ainda, vou abrir um outro PR para ajustar nas próximas semanas. A ideia desse PR aqui é revisar só os endpoints de Category.

2022-09-09 18:50 UTC, karenkrieger approved these changes
LGTM

2022-09-09 19:27 UTC, merged