Added add cart item & updated cart items endpoints
vtex/openapi-schemas pull request #660
Opened 2022-11-09 17:34 UTC by ricardoaerobr

#### Types of changes
- [X] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to generate documentation for the "Add cart items" endpoint in Dev. Portal and update the description/ parameters of the "Update cart items" endpoint. (JIRA EDU-8206).

2022-11-10 21:46 UTC, karenkrieger requested changes

2022-11-10 21:46 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                            "description": "Total value of the order without separating cents. For example, $24.99 is represented `2499`."
```suggestion
                                            "description": "Total value of the order without separating cents. For example, $24.99 is represented as `2499`."
```

2022-11-10 21:46 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                            "description": "Shipping estimate. For instance, Three business days will be represented `3bd`."
```suggestion
                                                                            "description": "Shipping estimate. For instance, \"three business days\" will be represented as `3bd`."
```

2022-11-10 21:46 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                            "description": "Transit time. For instance, \"three business days\" is represented `3bd`."
```suggestion
                                                                            "description": "Transit time. For instance, \"three business days\" is represented as `3bd`."
```

2022-11-10 21:46 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                            "description": "Object containing information about the ordering of items within the orderForm.",
```suggestion
                                            "description": "Object containing information about the ordering of items within the `orderForm`.",
```

2022-11-11 12:34 UTC, ricardoaerobr commented on VTEX - Checkout API.json
> +                "description": "You can use this request to:\n\r\n\r1. Change the quantity of one or more items in a specific cart.\n\r2. 2. Remove an item from the cart (by sending the `quantity` va
Fixed.

2022-11-11 12:34 UTC, ricardoaerobr commented on VTEX - Checkout API.json
> +                        "description": "ID of the orderForm corresponding to the cart whose items you want to update.",
Fixed.

2022-11-11 12:34 UTC, ricardoaerobr commented on VTEX - Checkout API.json
> +                                            "description": "Total value of the order without separating cents. For example, $24.99 is represented `2499`."
Fixed.

2022-11-11 12:34 UTC, ricardoaerobr commented on VTEX - Checkout API.json
> +                                                                            "description": "Transit time. For instance, \"three business days\" is represented `3bd`."
Fixed.

2022-11-11 16:58 UTC, karenkrieger approved these changes
LGTM

2022-11-11 17:13 UTC, merged