add subscriptionData to orders open api schema
vtex/openapi-schemas pull request #662
Opened 2022-11-17 21:05 UTC by DannyC-BC

#### Types of changes
- [X] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2022-11-18 14:52 UTC, karenkrieger requested changes
Thanks for contributing to our API documentation! ✨ I left some comments in the review to align the code with our API documentation standards

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                            "type": "object",
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                      "type": "string",
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                      "format": "int32",
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                      "type": "object",
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                          "nullable":true
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                          "nullable":true,
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                              "nullable": true
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                              "nullable": true
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                          "type": "object",
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                              "nullable": true
Add `description`

2022-11-18 14:52 UTC, karenkrieger commented on VTEX - Orders API.json
> +                                                              "nullable": true
Add `description`

2023-07-20 17:36 UTC, julia-rabello commented
@Isabella-Veloso this is an external contribution from last year, adding `subscriptionData` information to the [Get order](https://developers.vtex.com/docs/api-reference/orders-api#get-/api/oms/pvt/orders/-orderId-) endpoint. Can you review these proposed changes and contribute with the missing descriptions for this to be published?

2024-03-21 14:12 UTC, Isabella-Veloso commented
This PR deprecated, since the documentation has already been updated with this content.

2024-03-21 14:12 UTC, closed without merging