Content mkd Marketplace API
vtex/openapi-schemas pull request #708
Opened 2023-01-19 02:36 UTC by anabaarbosa

A descrição dos seguintes endpoints foram atualizados:

-UpsertSellerRequest
-GetListSellers
-UpdateSeller
-GetRetrieveSeller
-CreateFeed
-UpsertMapping

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-01-23 18:02 UTC, karenkrieger requested changes

2023-01-23 18:02 UTC, karenkrieger commented on VTEX - Marketplace APIs.json
> +                "description": "Marketplace operator may call this endpoint to retrieve information about a specific seller by filtering by ID. It is also possible to filter results by sales channel
O link tá quebrado

2023-01-30 18:59 UTC, jumeyermattosarruda requested changes

2023-01-30 18:59 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "This endpoint lists all Sellers. This call's results can be filtered by [trade policies](https://help.vtex.com/en/tutorial/como-funciona-uma-politica-comercial--6Xef8P
```suggestion
                "description": "This endpoint lists all Sellers. This call's results can be filtered by [trade policies](https://help.vtex.com/en/tutorial/como-funciona-uma-politica-comercial--6Xef8PZiFm40kg2STrMkMV) through the `sc` query param. \n\n>\u26A0 This documentation refers to the updated version of the Sellers' endpoints in our Marketplace API. If you are doing this integration for the first time, we recommend that you follow the updated documentation. If you are still using the Legacy version of Sellers endpoints, check the [Catalog API documentation](https://developers.vtex.com/docs/api-reference/catalog-api-seller).",
```

2023-01-30 18:59 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "This endpoint lists all Sellers. This call's results can be filtered by [trade policies](https://help.vtex.com/en/tutorial/como-funciona-uma-politica-comercial--6Xef8P
Removendo o #master-data por não ser relevante esse heading especificamente.

2023-01-30 18:59 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "Marketplace operator may call this endpoint to retrieve information about a specific seller by filtering by ID. It is also possible to filter results by sales channel
```suggestion
                "description": "Marketplace operator may call this endpoint to retrieve information about a specific seller by filtering by ID. It is also possible to filter results by sales channel or [trade policy](https://help.vtex.com/en/tutorial/como-funciona-uma-politica-comercial--6Xef8PZiFm40kg2STrMkMV) through the `sc` query param. \n\n> \u26A0 This documentation refers to the updated version of the Sellers' endpoints in our Marketplace API. If you are doing this integration for the first time, we recommend that you follow the updated documentation. If you are still using the Legacy version of Sellers endpoints, check the [Catalog API documentation](https://developers.vtex.com/docs/api-reference/catalog-api-seller).",
```

2023-01-30 18:59 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "Marketplace operator may call this endpoint to retrieve information about a specific seller by filtering by ID. It is also possible to filter results by sales channel
Removendo o #master-data por não ser relevante esse heading especificamente.

2023-01-30 18:59 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +                "description": "Marketplace operator may call this endpoint to retrieve information about a specific seller by filtering by ID. It is also possible to filter results by sales channel
Sobre o link do Catalog API, os corretos estão contidos nesse heading 👇 . E aí cada endpoint vai ter um link apropriado ([ex](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/seller/list))  
<img width="224" alt="image" src="https://user-images.githubusercontent.com/83723439/215563701-5636fc53-169b-48de-a4ec-4fc4037d2b3c.png">

2023-02-03 15:32 UTC, anabaarbosa commented
@karenkrieger ajustei o link, pode revisar, por favor?

2023-02-03 15:36 UTC, karenkrieger approved these changes
LGTM

2023-02-03 21:22 UTC, anabaarbosa commented
Vou reabrir, pois deram muitos conflitos.

2023-02-03 21:22 UTC, closed without merging