Update fulfillment simulation external seller
vtex/openapi-schemas pull request #736
Opened 2023-01-27 16:53 UTC by jumeyermattosarruda

This PR adds content that was previously in markdown in Readme, to the External Seller - Fulfillment Endpoint API Reference. More details were added to the call's description, and the response body was fully documented. 

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-01-27 20:00 UTC, jumeyermattosarruda commented on VTEX - Marketplace Protocol.json
> +                                                "availableDeliveryWindows": [
Não sei por que o spectral está acusando esse erro, sendo que o `availableDeliveryWindows` está declarado no exemplo, como deve ser.

2023-01-27 20:00 UTC, jumeyermattosarruda commented on VTEX - Marketplace Protocol.json
> +                                                                "availableDeliveryWindows": [
Não sei por que o spectral está acusando esse erro, sendo que o `availableDeliveryWindows` está declarado no exemplo, como deve ser.

2023-01-27 20:00 UTC, jumeyermattosarruda commented on VTEX - Marketplace Protocol.json
> +                                                        "availableDeliveryWindows": [
Não sei por que o spectral está acusando esse erro, sendo que o `availableDeliveryWindows` está declarado no exemplo, como deve ser.

2023-01-27 20:00 UTC, jumeyermattosarruda commented on VTEX - Marketplace Protocol.json
> +                                                        "availableDeliveryWindows": [
Não sei por que o spectral está acusando esse erro, sendo que o `availableDeliveryWindows` está declarado no exemplo, como deve ser.

2023-01-27 22:50 UTC, karenkrieger requested changes

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                "description": "This endpoint may be called upon by VTEX for fulfillment simulation in the external seller different contexts. See examples below.\n\nWhen a [Notification request](htt
https://developers.vtex.com/vtex-rest-api/reference/notification: link quebrado

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                "availableDeliveryWindows": [
AHH! Saquei o erro. Tem vários objetos dentro de `slas`. Como o primeiro objeto não tem `availableDeliveryWindows` ele aponta como erro no schema

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                                    "description": "Service ID",
```suggestion
                                                                    "description": "Service ID.",
```

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                          "description": "Promotions applied to the SKU",
```suggestion
                                                          "description": "Promotions applied to the SKU.",
```

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                                    "description": "Contains the data about the pickup point. If you don’t want to send this, use the value null.",
```suggestion
                                                                    "description": "Contains the data about the pickup point. If you don’t want to send this, use the value `null`.",
```

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                                    "type": "object",
```suggestion
                                                                    "type": "object",
                                                                    "nullable": true,
```

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                                            "description": "true if it is a pickup point.",
```suggestion
                                                                            "description": "`true` if it is a pickup point.",
```

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                                                    "description": "Name of the person who will receive the product. May be sent as null.",
```suggestion
                                                                                    "description": "Name of the person who will receive the product. May be sent as `null`.",
```

2023-01-27 22:50 UTC, karenkrieger commented on VTEX - Marketplace Protocol.json
> +                                                                                    "description": "Complement of the pickup point address.¸",
```suggestion
                                                                                    "description": "Complement of the pickup point address.",
```

2023-01-27 22:51 UTC, karenkrieger commented
Para resolver os erros 🔴 é só deletar o primeiro objeto da lista de `slas`

2023-02-01 19:24 UTC, karenkrieger approved these changes
LGTM

2023-02-01 19:34 UTC, merged