add GiftCard API descriptions
vtex/openapi-schemas pull request #774
Opened 2023-02-17 20:49 UTC by marcellasiqueira

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-02-23 13:52 UTC, henriquessb commented on VTEX - Giftcard API.json
> +                "description": "Creates a GiftCard for a specific user.\r\n\r\n## Warning\r\n\r\n- The field `userProfileId` should be filled with a value that identifies the client. It is the ID its
```suggestion
                "description": "Creates a GiftCard for a specific user.\r\n\r\n## Warning\r\n\r\n- The field `userProfileId` should be filled with a value that identifies the client. It is the ID itself.\r\n- The field `expiringDate` should be filled in ISO 8601 format `YYYY-MM-DDThh:mm:ss.fff`.\r\n\r\n>ℹ️️ The `redemptionCode` field for a Gift Card is auto-generated on creation and cannot be set to an arbitrary value.",
```

2023-02-28 17:31 UTC, karenkrieger requested changes

2023-02-28 18:02 UTC, henriquessb commented on VTEX - Giftcard API.json
> +                "description": "Creates a GiftCard for a specific user.\r\n\r\n## Warning\r\n\r\n- The field `userProfileId` should be filled with a value that identifies the client. It is the ID its
Só para ajudar na discussão, o uso mais predominante na minha experiência é `GiftCard` e é o que eu escolheria.

Mas se for bater o martelo para mudar em toda a documentação, eu acho melhor ver com o time de produto e ver se é tudo uma coisa só ou se tem significados diferentes para cada forma. Ex.: `GiftCard` pode ser algo que utilizamos só dentro da VTEX, mas `gift card` é o vale-presente genérico usado na indústria.

2023-02-28 18:39 UTC, marcellasiqueira commented on VTEX - Giftcard API.json
> +                "description": "Creates a GiftCard for a specific user.\r\n\r\n## Warning\r\n\r\n- The field `userProfileId` should be filled with a value that identifies the client. It is the ID its
também acho `GiftCard` melhor, vou nesse mesmo ✌️ mas o ponto de @henriquessb é válido

2023-03-03 19:50 UTC, karenkrieger approved these changes
LGTM

2023-03-13 22:21 UTC, merged