Update mkp overview
vtex/openapi-schemas pull request #795
Opened 2023-03-07 02:30 UTC by anabaarbosa

Add of Endpoints available at Marketplace Overview

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-03-07 12:54 UTC, jumeyermattosarruda requested changes

2023-03-07 12:54 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +        "description": "The **Marketplace API** enables marketplaces and sellers hosted on VTEX to perform their collaborative operations.\r\n\r\n>\u26A0\uFE0F The marketplace must [create an appKey
Sugiro adicionar links pras docs que explicam mais sobre o produto que a API envolve. Ex. no Offer Management, adiciona o link do guia de integração, que é o que explica como usar esses endpoints https://developers.vtex.com/docs/guides/sent-offers-integration-guide-connectors

2023-03-07 12:58 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs.json
> +        "description": "The **Marketplace API** enables marketplaces and sellers hosted on VTEX to perform their collaborative operations.\r\n\r\n>\u26A0\uFE0F The marketplace must [create an appKey
Dá também pra dar um up na primeira frase com as sugestões indicadas no [template](https://github.com/vtex/openapi-schemas/blob/master/Template%20-%20API%20Reference%20Overview.md). O que mais que dá pra falar sobre o que essa API permite marketplaces e sellers fazerem? Quais endpoints são voltados pro seller e quais são pro marketplace? E se tivesse uma tabela mostrando essa relação? Ideias :)

2024-10-17 13:30 UTC, closed without merging

2024-10-17 13:31 UTC, anabaarbosa commented
Pr antigo e já mergeado em outro PR.