Update VTEX - MasterData API - v10.2.json
vtex/openapi-schemas pull request #816
Opened 2023-04-03 23:39 UTC by PedroAntunesCosta

Fixing the description of the Search endpoint, which was in the wrong place in the JSON.

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [x] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-04-04 15:39 UTC, karenkrieger approved these changes
LGTM

2023-04-05 21:37 UTC, julia-rabello requested changes

2023-04-05 21:37 UTC, julia-rabello commented on VTEX - MasterData API - v10.2.json
> +                "summary": "Use this endpoint to validate documents by clusters.\n\r\n\r> Learn more about Master Data [clusters](https://help.vtex.com/tutorial/como-criar-um-cluster-de-clientes--fre
```suggestion
                "summary": "Validate document by clusters",
```

2023-04-05 21:37 UTC, julia-rabello commented on VTEX - MasterData API - v10.2.json
> +                "description": "Validate document by clusters.",
```suggestion
                "description": "Use this endpoint to validate documents by clusters.\n\r\n\r> Learn more about Master Data [clusters](https://help.vtex.com/tutorial/como-criar-um-cluster-de-clientes--frequentlyAskedQuestions_1724).",
```

2023-04-05 21:37 UTC, julia-rabello commented on VTEX - MasterData API - v10.2.json
> +                "summary": "Creates partial document",
```suggestion
                "summary": "Create partial document",
```

2023-04-06 12:02 UTC, julia-rabello approved these changes

2023-04-06 13:59 UTC, merged