Fixing antifraud provider endpoints
vtex/openapi-schemas pull request #826
Opened 2023-04-11 19:58 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to fix antifraud provider endpoints (EDU-8998).

2023-04-14 18:38 UTC, karenkrieger requested changes

2023-04-14 18:38 UTC, karenkrieger commented on VTEX - Antifraud Provider API.json
> +                        "description": "The original ip address from browser."
```suggestion
                        "description": "The original IP address from the browser."
```

2023-04-14 18:38 UTC, karenkrieger commented on VTEX - Antifraud Provider API.json
> +                        "description": "VTEX has a main Name for the store. This unique name is often used in url to access VTEX configurations."
```suggestion
                        "description": "VTEX has a main Name for the store. This unique name is often used in URL to access VTEX configurations."
```

2023-04-14 18:38 UTC, karenkrieger commented on VTEX - Antifraud Provider API.json
> +                        "description": "Provider transaction ID. The ID of this transaction must be in the response. The antifraud provider MUST generates an unique transaction Id."
```suggestion
                        "description": "Provider transaction ID. The ID of this transaction must be in the response. The antifraud provider MUST generates a unique transaction Id."
```

2023-04-14 19:29 UTC, ricardoaerobr commented on VTEX - Antifraud Provider API.json
> +                        "description": "The original ip address from browser."
Fixed.

2023-04-14 19:30 UTC, ricardoaerobr commented on VTEX - Antifraud Provider API.json
> +                        "description": "VTEX has a main Name for the store. This unique name is often used in url to access VTEX configurations."
Fixed.

2023-04-14 19:31 UTC, ricardoaerobr commented on VTEX - Antifraud Provider API.json
> +                        "description": "Provider transaction ID. The ID of this transaction must be in the response. The antifraud provider MUST generates an unique transaction Id."
Fixed.

2023-04-17 18:13 UTC, karenkrieger approved these changes
LGTM

2023-04-17 18:30 UTC, merged