Get matcher information settings
vtex/openapi-schemas pull request #857
Opened 2023-05-30 16:25 UTC by anabaarbosa

New API to retrieve matcher configuration information in a marketplace account. API included in received suggestions/SKUs menu.

L464 - L542 (documentation)
L1717 - L1780 (response schema)

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-06-09 20:37 UTC, jumeyermattosarruda requested changes

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                "description": "This endpoint only retrieves configuration information from matchers in the marketplace account. If the account has no matcher configured, the response will be `404 No
Pensando na máxima de "every page is page one", que contexto você dá pros devs que chegaram de paraquedas nesse endpoint, pra entenderem tudo que precisam sobre ele? Senti falta de uma frase de início mais completa com mais contexto, do jeito que está é como se você já passasse batido por conceitos com o bonde andando. Perguntas que surgem, ao ler a primeira frase:
- O que é um matcher?
- Que configuration information? Configuração do que?
- Quem deve chamar esse endpoint, e qual o interesse de pegar infos sobre a configuração do matcher. 
- Qual a diferença entre account matcher settings vs. account approval configuration? 

Muitas dessas perguntas podem ser resolvidas linkando artigos do Help, por exemplo.

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                                            "hook-base-address": "http://portal.vtexinternal.com.br/api/u90/hooks",
Esse é minúsculo e com hífens mesmo?

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                                "description": "Minimum approval score set by the marketplace."
Mesma coisa pros valores de reject

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                        "description": "Array of objects that presents a list of matchers configured in the marketplace. If the marketplace has more than one matcher configured in the account, an arr
Adicionaria que "by default, the VTEX Matcher is set up automatically in VTEX accounts and has the XYZ matcherId". Aí checa com os devs qual o matcherId do Matcher da VTEX pra já indicar

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                        "description": "Arrays object that contains the rules defined for product approval.",
Dá pra complementar bastaaaante essas infos de `item` e `product`. É aqui que a maioria das configs vai acontecer. Que tipo de regra pode ser de fato configurada aqui? Como isso se relaciona com o que tá na [doc](https://help.vtex.com/en/tutorial/entendendo-a-pontuacao-do-vtex-matcher--tutorials_424) sobre regras de itens e produtos? Que itens? É o mesmo que SKU? Kd exemplos de como esses campos vêm na response, pra cada um?

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                                    "description": "The Matcher Id."
Adicionar `example` pra todos esses faltantes

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                                "description": "Bounce score set by marketplace."
adicionar `example` em todos os faltantes

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +            "responseGetAccountsMatcherSettings": {
Mesmo comentário de lá em cima sobre todos os campos estarem em maiúsculo

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                        "description": "List of specifications mapping."
O que é specifications mapping? Como essa descrição tá agregando algo além do que o título dela (specificationsMapping) já indica? 
Pensa sempre em trazer mais contexto pras descrições, ao invés de repetir o que dá pra interpretar do título

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                        "description": "This field determines the type of approval configuration applied to SKUs received from a seller. \n\nThe possible values include: \n\n-`default`, where the Mat
Como isso é diferente das rules aplicadas à items?

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                        "description": "This field determines the type of approval configuration applied to SKUs received from a seller. \n\nThe possible values include: \n\n-`default`, where the Mat
Mudaria a vírgula pra dois pontos. Ex:
- `default`: Where the Matcher reviews the SKU, and approves it based on its score.

2023-06-09 20:37 UTC, jumeyermattosarruda commented on VTEX - Marketplace APIs - Suggestions.json
> +                        "description": "This field determines the type of approval configuration applied to SKUs received from a seller. \n\nThe possible values include: \n\n-`default`, where the Mat
Pensa que nossas regras editoriais do guia de estilo também se aplicam à dev docs

2023-06-15 20:13 UTC, anabaarbosa commented
@jumeyermattosarruda alterações realizadas

2023-06-23 12:46 UTC, jumeyermattosarruda submitted a review, later dismissed

2023-06-26 15:31 UTC, jumeyermattosarruda approved these changes

2023-06-26 15:33 UTC, merged