Template open API
vtex/openapi-schemas pull request #869
Opened 2023-06-16 15:38 UTC by anabaarbosa

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +            "description": "VTEX server url",
```suggestion
            "description": "VTEX server URL.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                    "description": "Your VTEX account name"
```suggestion
                    "description": "Your VTEX account name."
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +        "title": "Pets Api",
```suggestion
        "title": "API name",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +        "title": "Pets Api",
O que acham de substituir assim?

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                "description": "Describe the purpose of this path and who should use it.",
```suggestion
                "description": "Describe the purpose of this endpoint and who should use it.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                    "pets"
```suggestion
                    "Category that will render on Developer Portal"
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "description": "How many items to return at one time (max 100)",
```suggestion
                        "description": "How many items to return at one time (max 100).",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "description": "An paged array of pets",
```suggestion
                        "description": "A paged array of pets.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                    "description": "In the requestBody will be informed the data for insertion of new pets in the adoption list. This data must be sent in JSON format.",
```suggestion
                    "description": "In the requestBody will be informed of the data for insertion of new pets in the adoption list. This data must be sent in JSON format.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                    "description": "In the requestBody will be informed the data for insertion of new pets in the adoption list. This data must be sent in JSON format.",
Não sei se deixaria a frase `This data must be sent in JSON format.` porque nem sempre é o caso. Acho que talvez colocar **This data usually is an `application/json`.**

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                    "200": {
Faltou adicionar o schema da response

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "description": "Animal color",
```suggestion
                        "description": "Animal color.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "description": "Animal breed",
```suggestion
                        "description": "Animal breed.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "description": "Animal carry",
```suggestion
                        "description": "Animal carry.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "description": "Animal age",
```suggestion
                        "description": "Animal age.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "example": "TRUE"
```suggestion
                        "example": true
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                                        "example": "TRUE"
```suggestion
                                        "example": true
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                                        "description": "Inform if the animal is vaccinated or not. \n\n `TRUE` = vaccinated animal or `FALSE` = unvaccinated animal.",
```suggestion
                                        "description": "Inform if the animal is vaccinated or not. \n\n `true` = vaccinated animal or `false` = unvaccinated animal.",
```

2023-06-16 18:26 UTC, karenkrieger commented on VTEX - TEMPLATE.json
> +                        "description": "Inform if the animal is vaccinated or not. \n\n `TRUE` = vaccinated animal or `FALSE` = unvaccinated animal.",
```suggestion
                        "description": "Inform if the animal is vaccinated or not. \n\n `true` = vaccinated animal or `false` = unvaccinated animal.",
```

2023-06-16 20:48 UTC, PedroAntunesCosta requested changes
Obrigado pelo PR, @anabaarbosa !

Fiz sugestões, mas queria deixar algumas direções gerais que acho bem importantes para corrigir no template:

- Remover todos os `title`.
- Deixar completamente genérico, onde todos os valores são place-holders ou comuns a todas as APIs. Ou seja, não terá menção a pets, etc.
- É muito importnte seguir a [checklist](https://github.com/vtex/openapi-schemas/blob/master/OpenAPI%20Checklist.md), mesmo que imperfeita, é onde está registrado o padrão atual. Exemplo: no request body todos os campos escalares (nem array nem objeto) tem que ter `example`, já na response, só `type` e `description` basta.
- Inserir um exemplo de parâmetro de `path`.
- Considerar essas atualizações discutidas [aqui](https://vtex.slack.com/archives/C0524C7S32B/p1686932977501339).

2023-06-16 20:48 UTC, PedroAntunesCosta commented on VTEX - TEMPLATE.json
> +        "/pets": {
```suggestion
        "{path}": {
```

2023-06-16 20:48 UTC, PedroAntunesCosta commented on VTEX - TEMPLATE.json
> +                "description": "Describe the purpose of this path and who should use it.",
```suggestion
                "description": "{method-description}",
```

2023-06-16 20:48 UTC, PedroAntunesCosta commented on VTEX - TEMPLATE.json
> +                "summary": "List all pets",
```suggestion
                "summary": "{method-summary}",
```

2023-06-21 20:45 UTC, closed without merging

2023-06-21 20:45 UTC, anabaarbosa commented
create new template for KR