Template Open API
vtex/openapi-schemas pull request #874
Opened 2023-06-21 20:44 UTC by anabaarbosa

New template openapi-schemas

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [x] No, but I am going to.

2023-06-21 21:45 UTC, PedroAntunesCosta requested changes

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +        "contact": {}
```suggestion
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                    "Category that will render on Developer Portal"
```suggestion
                    "{applicable-tags}"
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                    "Category that will render on Developer Portal"
These are not rendered anymore. Maybe in the future.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                        }
```suggestion
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                        }
Esse param não é comum a todas as APIs

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                        "type": "string",
```suggestion
                                        "type": "{field1-type}",
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                        "example": "{field1-value}"
```suggestion
                                        "example": {field1-value-example}
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                        "example": "{field1-value}"
Sugiro remover as aspas porque só são usadas para strings.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                        "type": "string",
Sugiro ter um exemplo de um campo completamente genérico.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                    "{field2}",
```suggestion
                                    "{field2-array-example}",
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                    "{field3}"
```suggestion
                                    "{field3-object-example}"
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                    "{field2}": {
```suggestion
                                    "{field2-array-example}": {
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "{field2.3}"
```suggestion
                                                "{field2.[].1}",
                                                "{field2.[].2}",
                                                "{field2.[].3}"
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "{field2.3}"
Pensei em colocar esse formato pra deixar explícito que todos esses campos existem para cada item do array.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "{field2.1}": {
```suggestion
                                                "{field2.[].1}": {
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                    "description": "{field2.1-description}."
Adicionar `example`.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "{field2.2}": {
```suggestion
                                                "{field2.[].2}": {
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                    "description": "{field2.2-description}."
Adicionar `example`.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "{field2.3}": {
```suggestion
                                                "{field2.[].3}": {
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                    "description": "{field2.2-description}."
```suggestion
                                                    "description": "{field2.[].2-description}."
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                    "description": "{field2.3-description}."
```suggestion
                                                    "description": "{field2.[].3-description}."
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                    "{field3}": {
```suggestion
                                    "{field3-object-example}": {
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "type": "string"
Adicionar `description` e `example`.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "format": "{value-format}"
```suggestion
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "type": "integer",
Adicionar `description` e `example`.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "type": "boolean"
Adicionar `description` e `example`.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                        "required": true
Não usamos `example` nem `required` para request body. Essa informação já está na parte de cada campo acima. Recomendo só dar uma olhada se acertei nas chaves e colchetes. Talvez seja mais fácil excluir manualmente no VSCode 😅

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                        },
```suggestion
                            }
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                        "required": true
```suggestion
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                        },
Adicionar schemas dos campos 2 e 3.

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                            "{field1}": {
```suggestion
                                            "{response-field1}": {
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                            "{field1}": {
Pensei nisso pra diferenciar dos campos acima, já que request e response tem requisitos diferentes. O que acha?

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                                "description": "{field1-description}."
```suggestion
                                                "type": "{response-field1-type}",
                                                "description": "{response-field1-description}."
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                                            "{field3}":"{field3-value}"
```suggestion
                                            "{response-field1}": "{response-field1-value}",
                                            "{response-field2}": "{response-field2-value}",
                                            "{response-field3}":"{response-field3-value}"
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +                        "deprecated": false
```suggestion
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +            "name": "Category that will render on Developer Portal"
```suggestion
            "{category-name}": "{category-description}",
            "{category2-name}" "{category2-description}"
```

2023-06-21 21:45 UTC, PedroAntunesCosta commented on VTEX - Template openAPI.json
> +            "name": "Category that will render on Developer Portal"
Exemplificando como fica com mais de uma tag.

2023-06-23 19:42 UTC, karenkrieger requested changes

2023-06-23 19:42 UTC, karenkrieger commented on VTEX - Template openAPI.json
> +                            "example": "application/json"
```suggestion
                            "default": "application/json"
```

2023-06-23 19:42 UTC, karenkrieger commented on VTEX - Template openAPI.json
> +                            "example": "application/json"
```suggestion
                            "default": "application/json"
```

2023-06-23 21:56 UTC, PedroAntunesCosta submitted a review, later dismissed
LGTM

2023-06-26 20:56 UTC, merged