GiftCard API Transactions endpoints updated
vtex/openapi-schemas pull request #892
Opened 2023-07-06 18:00 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

PR created to update field descriptions in GiftCard API endpoints (EDU-10227 and EDU-10198).

2023-07-06 19:03 UTC, julia-rabello requested changes

2023-07-07 11:54 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                                            "description": "Gift card `id`."
Modificado para Gift card identification.

2023-07-07 11:55 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                                            "description": "Gift card redemption token."
Aqui foi um erro de duplicação mesmo. O correto para a segunda descrição é Gift card redemption code.

2023-07-07 11:56 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                                            "description": "Giftcard current balance. For Gift Cards newly created, the balance will be 0.0.",
Fixed.

2023-07-07 12:00 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "description": "Date information."
Vou utilizar o padrão que vi em outros endpoints -> "Date of the transaction (YYYY-MM-DDThh:mm:ss.fff (ISO 8601 format)."

2023-07-07 12:07 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                                            "description": "Giftcard current balance. For Gift Cards newly created, the balance will be 0.0.",
Neste caso 0.0 mesmo.

2023-07-07 12:12 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "description": "Description information."
Transaction description.

2023-07-07 12:14 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
>                  "default": {
Fixed.

2023-07-07 12:14 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
>                  "default": {
Fixed.

2023-07-07 12:15 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "description": "Value information."
Transaction value.

2023-07-07 12:19 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "description": "Operation information."
Operation information (`credit` or `debit`).

2023-07-07 12:27 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
>                  "type": "object",
Boa idéia. Deletei o `CancelGiftCardTransactionRequest` e modifiquei as chamadas do `SettleGiftCardTransactionRequest` para `GiftCardTransactionRequest`.

2023-07-07 12:42 UTC, julia-rabello requested changes

2023-07-07 12:42 UTC, julia-rabello commented on VTEX - Giftcard API.json
>                                              "type": "integer",
```suggestion
                                            "type": "number",
```

2023-07-07 12:42 UTC, julia-rabello commented on VTEX - Giftcard API.json
>                                              "format": "int32"
```suggestion
                                            "description": "Giftcard current balance. For newly created giftcards, the balance will be 0.0."
```

2023-07-07 12:42 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "Date of the transaction (YYYY-MM-DDThh:mm:ss.fff (ISO 8601 format)."
```suggestion
                        "description": "Date of the transaction in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`)."
```

2023-07-07 12:42 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "Date of the transaction (YYYY-MM-DDThh:mm:ss.fff (ISO 8601 format)."
```suggestion
                        "description": "Date of the transaction in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`)."
```

2023-07-07 12:42 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "Date of the transaction (YYYY-MM-DDThh:mm:ss.fff (ISO 8601 format)."
```suggestion
                        "description": "Date of the transaction in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`)."
```

2023-07-07 12:45 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
>                                              "type": "integer",
Adjusted.

2023-07-07 12:49 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "description": "Date of the transaction (YYYY-MM-DDThh:mm:ss.fff (ISO 8601 format)."
Adjusted.

2023-07-07 12:50 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "description": "Date of the transaction (YYYY-MM-DDThh:mm:ss.fff (ISO 8601 format)."
Adjusted.

2023-07-07 12:50 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "description": "Date of the transaction (YYYY-MM-DDThh:mm:ss.fff (ISO 8601 format)."
Adjusted.

2023-07-07 16:27 UTC, julia-rabello requested changes

2023-07-07 16:27 UTC, julia-rabello commented on VTEX - Giftcard API.json
>                                              "format": "int32"
```suggestion
                                            "description": "Giftcard current balance. For newly created giftcards, the balance will be 0.0."
```

2023-07-07 16:30 UTC, julia-rabello requested changes

2023-07-07 16:30 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                                            "format": "int32"
```suggestion
                                            "description": "Giftcard current balance. For newly created giftcards, the balance will be 0.0."
```

2023-07-07 16:32 UTC, julia-rabello submitted a review, later dismissed

2023-07-07 16:52 UTC, julia-rabello approved these changes

2023-07-07 16:53 UTC, merged