Update GiftCard API description
vtex/openapi-schemas pull request #935
Opened 2023-08-03 17:49 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

PR created to update the GiftCard API description (EDU-4150).

2023-08-03 20:30 UTC, julia-rabello requested changes

2023-08-03 20:30 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +        "description": ">ℹ️ Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for develo
Recomendo usar markdown escapado para a tabela aqui, em vez de HTML.

Com markdown, a tabela vai respeitar a estilização do Dev Portal (fonte, etc), mas com HTML acho que não.

2023-08-04 12:59 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +        "description": ">ℹ️ Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for develo
Júlia, o HTML está fora do table. O formato dos dados que estão dentro do table está seguindo a mesma lógica do que existe no List Payment Provider Manifest endpoint. Então, acredito que não vamos ter problema para renderizar.

2023-08-04 14:53 UTC, karenkrieger approved these changes
LGTM

2023-08-04 15:02 UTC, julia-rabello approved these changes

2023-08-04 15:03 UTC, merged