Update Gift cards endpoint name and descriptions
vtex/openapi-schemas pull request #951
Opened 2023-08-09 22:04 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to update name and descriptions (GiftCard API and GiftCard Provider Protocol API) (EDU-9115).

2023-08-09 22:36 UTC, julia-rabello requested changes

2023-08-09 22:36 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                "description": "This request can be used to:\r\n\r\n1. Cancel a transaction for a specific gift card.\r\n\r\n2. Cancel a item reservation or create a refund.",
```suggestion
                "description": "This request can be used to:\r\n\r\n1. Cancel a transaction for a specific gift card.\r\n\r\n2. Cancel an item's reservation or create a refund.",
```

2023-08-09 22:36 UTC, julia-rabello commented on VTEX - Giftcard Provider Protocol.json
> +				"description": "Creates a gift card for a specific user in a gift card provider.\r\n\r\n## Warning\r\n\r\n- The field `profileId` should be filled with a value that identifies the client. It is t
Sugestão: formatar warning como callout com `>⚠️`

2023-08-09 22:36 UTC, julia-rabello commented on VTEX - Giftcard Provider Protocol.json
> +				"description": "This request can be used to:\r\n\r\n1. Cancel a transaction for a specific gift card in a gift card provider.\r\n\r\n2. Cancel a item reservation or create a refund.",
```suggestion
				"description": "This request can be used to:\r\n\r\n1. Cancel a transaction for a specific gift card in a gift card provider.\r\n\r\n2. Cancel an item's reservation or create a refund.",
```

2023-08-10 12:12 UTC, ricardoaerobr commented on VTEX - Giftcard Provider Protocol.json
> +				"description": "Creates a gift card for a specific user in a gift card provider.\r\n\r\n## Warning\r\n\r\n- The field `profileId` should be filled with a value that identifies the client. It is t
Removi esta informação, pois já consta nos campos a serem preenchidos.

2023-08-10 13:37 UTC, julia-rabello approved these changes

2023-08-10 13:37 UTC, merged