Update PIX payload info
vtex/openapi-schemas pull request #974
Opened 2023-08-25 19:54 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to fix the PIX payload information (EDU-10610).

2023-08-25 20:10 UTC, karenkrieger submitted a review, later dismissed
LGTM

2023-08-25 20:36 UTC, julia-rabello requested changes
O body do Pix está com alguns `}`, `]`, `,` e `'` incorretos. No cURL fica difícil de ver isso, principalmente sem indentação, mas transferindo para um arquivo json fica mais fácil. Segue abaixo o trecho revisado:

```bash
curl --location --request POST 'https://{{providerApiEndpoint}}/payments' \
--header 'X-VTEX-API-AppKey: {{X-VTEX-API-AppKey}}' \
--header 'X-VTEX-API-AppToken: {{X-VTEX-API-AppToken}}' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw curl --location --request GET '' \
--header 'Content-Type: application/json' \
--data-raw '{
    "reference": "32478982",
    "orderId": "v967373115140abc",
    "transactionId": "D3AA1FC8372E430E8236649DB5EBD08E",
    "paymentId": "F5C1A4E20D3B4E07B7E871F5B5BC9F91",
    "paymentMethod": "Pix",
    "paymentMethodCustomCode": "null",
    "merchantName": "mystore",
    "value": "4307.23",
    "currency": "BRL",
    "installments": "1",
    "deviceFingerprint": "15ace369587ha",
    "card": {
        "holder": "null",
        "number": "null",
        "csc": "null",
        "expiration": {
            "month": "null",
            "year": "null"
        }
    },
    "miniCart": {
        "shippingValue": "11.44",
        "taxValue": "10.01",
        "buyer": {
            "id": "c1245228-1c68-11e6-94ac-0afa86a846a5",
            "firstName": "John",
            "lastName": "Doe",
            "document": "01234567890",
            "documentType": "cpf",
            "email": "john.doe@example.com",
            "phone": "+5521999999999"
        },
        "shippingAddress": {
            "country": "BRA",
            "street": "Praia de Botafogo St.",
            "number": "300",
            "complement": "3rd Floor",
            "neighborhood": "Botafogo",
            "postalCode": "22250040",
            "city": "Rio de Janeiro",
            "state": "RJ"
        },
        "billingAddress": {
            "country": "BRA",
            "street": "Brigadeiro Faria Lima Avenue",
            "number": "4440",
            "complement": "10th Floor",
            "neighborhood": "Itaim Bibi",
            "postalCode": "04538132",
            "city": "São Paulo",
            "state": "SP"
        },
        "items": [
            {
                "id": "132981",
                "name": "My First Product",
                "price": 2134.90,
                "quantity": 2,
                "discount": 5.00
            },
            {
                "id": "123242",
                "name": "My Second Product",
                "price": 21.98,
                "quantity": 1,
                "discount": 1.00
            }
        ]
    },
    "url": "https://admin.mystore.example.com/orders/v32478982",
    "callbackUrl": "https://api.example.com/some-path/to-notify/status-changes?an=mystore",
    "returnUrl": "https://mystore.example.com/checkout/order/v32478982"
}'
```

Outro ponto que não sei se é erro ou intencional: alguns valores nulos estão declarados como "null", com as aspas. Exemplo:     `"paymentMethodCustomCode": "null",`. É isso mesmo? Geralmente viria simplesmente `"paymentMethodCustomCode": null`, sem aspas.

2023-08-25 20:38 UTC, julia-rabello commented
Outras sugestões gerais:

- Tornar o json indentado nos cURLs para facilitar a legibilidade (acredito que funcione da mesma forma, porque no Postman funciona).

- Mudar o tipo de code block das responses de `bash` para `json` para aplicar o syntax highlighting correto.

2023-08-28 18:45 UTC, julia-rabello approved these changes

2023-08-28 19:34 UTC, merged