EDU-10587 update shippingEstimateDate & EDU-10555 add attachmentOfferings objetcs
vtex/openapi-schemas pull request #983
Opened 2023-09-11 16:53 UTC by geisecosta

#### Types of changes
- [x] New content (endpoints, descriptions or fields from scratch)
- [ ] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [ ] No, but I am going to.

2023-09-13 17:17 UTC, karenkrieger requested changes

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                            "nullable": true,
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "nullable": true
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "nullable": true
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "Schema of the content declared in the field `attachmentOfferings`.",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
>                                                                              "description": "Shipping estimate. For instance, \"three business days\" will be represented as `3bd`."
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
>                                                                              "nullable": true
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                            "nullable": true,
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "Name of the attachment.",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "If the attachment is required (`true`) or not (`false`).",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "Schema of the content declared in the field `attachmentOfferings`.",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
>                                                                              "description": "Shipping estimate. For instance, Three business days will be represented `3bd`."
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                            "description": "When using the query parameter `individualShippingEstimates=true`, it will contain the estimated shipping d
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "Name of the attachment.",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "type": "boolean",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                    "schema": {
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
>                                                                              "description": "Shipping estimate. For instance, Three business days will be represented `3bd`."
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
>                                                                              "nullable": true
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "Name of the attachment.",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "If the attachment is required (`true`) or not (`false`).",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "Schema of the content declared in the field `attachmentOfferings`.",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
>                                                                              "description": "Shipping estimate. For instance, Three business days will be represented `3bd`."
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "nullable": true
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                            "description": "When using the query parameter `individualShippingEstimates=true`, it will contain the estimated shipping d
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                                    "description": "If the attachment is required (`true`) or not (`false`).",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                                    "description": "Schema of the content declared in the field `attachmentOfferings`.",
Adicionar `example`

2023-09-13 17:17 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                                                                                        "description": "When using the query parameter `individualShippingEstimates=true`, it will contain the estimate
Adicionar `example`

2023-09-18 10:21 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                                    "description": "When using the query parameter `individualShippingEstimates=true`, it will contain the estimated shipping date, oth
@karenkrieger, eu adicionei o example como parte da `description`. É desta forma que ficaria?
<img width="1050" alt="image" src="https://github.com/vtex/openapi-schemas/assets/136460310/ae0fb588-951e-4d9c-85fb-7976750b5a63">

2023-09-18 10:21 UTC, geisecosta commented on VTEX - Checkout API.json
> +                                                                    "description": "List of attachments details.",
@karenkrieger, eu adicionei o example como parte da `description`. É desta forma que ficaria?
<img width="873" alt="image" src="https://github.com/vtex/openapi-schemas/assets/136460310/68923d54-ec8a-4459-bdbd-8a3a217cb49b">

2023-09-19 17:01 UTC, karenkrieger approved these changes
LGTM

2023-09-27 14:51 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:52 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:53 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:53 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:53 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:54 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:54 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:54 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:55 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:55 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:56 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:56 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-09-27 14:56 UTC, karenkrieger commented on VTEX - Checkout API.json
> +                            "default": false
```suggestion
                            "example": true

```

2023-10-10 18:57 UTC, karenkrieger approved these changes
LGTM

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Aqui tem um espaço antes de cada string, é isso mesmo? (Entre as aspas e o texto, tem um espaço que parece desnecessário)

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                            ]
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                        " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                        " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                        " 4 week"
Mesma coisa do comentário anterior

2023-10-31 18:22 UTC, julia-rabello commented on VTEX - Checkout API.json
> +                                                                        " 4 week"
Mesma coisa do comentário anterior

2023-11-09 14:24 UTC, julia-rabello approved these changes

2023-12-12 11:45 UTC, closed without merging