23H2KR5 GiftCard API update
vtex/openapi-schemas pull request #992
Opened 2023-09-27 21:06 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (endpoints, descriptions or fields from scratch)
- [X] Improvement (make an endpoint's title or description even better)
- [ ] Spelling and grammar accuracy (self-explanatory)

### Changelog
Do not forget to update your changes to our Developer Portal's changelog. Did you create a release note?
- [ ] Yes, I already created a release note about this change.
- [X] No, but I am going to.

PR created to update the GiftCard API (23H2KR5) (EDU-10333)

2023-09-27 21:50 UTC, julia-rabello requested changes

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +        "description": ">ℹ️ Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for develo
```suggestion
        "description": ">ℹ️ Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about Payments and is organized by focusing on the developer's journey.\r\n\r\nThe Gift Card is a payment method configured as a cash value associated with a client. It is used to grant a discount on the value of the order at the store. A gift card works as a **payment method**, **not a promotion**.\r\n\r\nIn VTEX's native gift card system, you can choose to create a new gift card either through [Admin VTEX](https://help.vtex.com/en/tutorial/gift-card--tutorials_995) or [API](https://developers.vtex.com/docs/api-reference/giftcard-api#post-/giftcards). However, there are specific conditions to be observed when generating gift cards by one of these two methods.\r\n\r\n<table>\r\n    <tr>\r\n        <th>Specifications</th>\r\n        <th>Admin VTEX</th>\r\n        <th>GiftCard API</th>\r\n    </tr>\r\n    <tr>\r\n        <td><b>Initial value</b></td>\r\n        <td>You can create gift cards with any value.</td>\r\n        <td>All gift cards are generated with no value (balance = 0). After its creation, you need to use VTEX Admin or the <a href=\"https://developers.vtex.com/docs/api-reference/giftcard-api#post-/giftcards/-giftCardId-/transactions\">Create GiftCard Transaction</a> endpoint to add any balance amount.</td>\r\n    </tr>\r\n    <tr>\r\n        <td><b>Ownership restriction</b></td>\r\n        <td>You can create gift cards with or without a user assigned to them.</td>\r\n        <td>All gift cards must be created with a <code>profileId</code> associated to them.</td>\r\n    </tr>\r\n    <tr>\r\n        <td><b>User data identification</b></td>\r\n        <td>Customer ID is the field with data that identifies a specific customer, such as CPF or CNPJ in Brazil.</td>\r\n        <td><code>profileId</code> is the field with data that identifies a specific customer).</td>\r\n    </tr>\r\n    <tr>\r\n        <td><b>Additional Settings</b></td>\r\n        <td>You can use checkboxes to select whether a gift card will be: <ul><li><b>Restricted</b> (only a specific customer ID can use this gift card)</li> <li><b>Reloadable</b> (balance can be changed while it is still active)</li> <li><b>Reusable</b> (available for making new purchases with this gift card until its value is completely used up)</li></ul></td>\r\n        <td>You can use the following fields to configure the same conditions applied in VTEX Admin:\r\n        <ul><li><b>Restricted:</b> <code>restrictedToOwner</code></li> <li><b>Reloadable:</b> <code>multipleRedemptions</code></li> <li><b>Reusable:</b> <code>multipleCredits</code></li></ul></td>\r\n    </tr>\r\n</table>\r\n\r\n>⚠️ All GiftCard API endpoints are limited to 500 concurrent requests and 5000 requests per minute.\r\n\r\n## GiftCard API Index\r\n\r\n### Gift Card\r\n\r\n- `POST` [Create GiftCard](https://developers.vtex.com/docs/api-reference/giftcard-api#post-/giftcards)\r\n- `GET` [Get GiftCard by ID](https://developers.vtex.com/docs/api-reference/giftcard-api#get-/giftcards/-giftCardId-)\r\n- `POST` [List All GiftCards](https://developers.vtex.com/docs/api-reference/giftcard-api#post-/giftcards/_search)\r\n\r\n### Transaction\r\n\r\n- `POST` [Create GiftCard Transaction](https://developers.vtex.com/docs/api-reference/giftcard-api#post-/giftcards/-giftCardId-/transactions)\r\n- `GET` [Get GiftCard Transaction by ID](https://developers.vtex.com/docs/api-reference/giftcard-api#get-/giftcards/-giftCardId-/transactions/-transactionId-)\r\n- `GET` [List All GiftCards Transactions](https://developers.vtex.com/docs/api-reference/giftcard-api#get-/giftcards/-giftCardId-/transactions)\r\n- `GET` [Get GiftCard Transaction Authorizations](https://developers.vtex.com/docs/api-reference/giftcard-api#get-/giftcards/-giftCardId-/transactions/-transactionId-/authorization)\r\n- `POST` [Cancel GiftCard Transaction](https://developers.vtex.com/docs/api-reference/giftcard-api#post-/giftcards/-giftCardId-/transactions/-transactionId-/cancellations)\r\n- `GET` [List All GiftCard Transaction Cancellations](https://developers.vtex.com/docs/api-reference/giftcard-api#get-/giftcards/-giftCardId-/transactions/-transactionId-/cancellations)\r\n- `POST` [Settle GiftCard Transaction](https://developers.vtex.com/docs/api-reference/giftcard-api#post-/giftcards/-giftCardId-/transactions/-transactionId-/settlements)\r\n- `GET` [List All GiftCard Transactions Settlements](https://developers.vtex.com/docs/api-reference/giftcard-api#get-/giftcards/-giftCardId-/transactions/-transactionId-/settlements)",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +        "description": ">ℹ️ Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for develo
Isso aqui tá certo? Assumi que sim porque seguia a mesma ordem da coluna do Admin, mas fiquei na dúvida porque parece que o `multipleRedemptions` tem mais a ver com a descrição de **Reusable** 👀 

> **Restricted**: `restrictedToOwner`
> **Reloadable**: `multipleRedemptions`
> **Reusable**: `multipleCredits`

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                "description": "Creates a gift card for a specific user.\r\n\r\n## Warning\r\n\r\n>ℹ️️ The `redemptionCode` field for a gift card is auto-generated on the creation and cannot be set t
```suggestion
                "description": "Creates a gift card for a specific user.\r\n\r\n>⚠️ The `redemptionCode` field is auto-generated during gift card creation and cannot be set to an arbitrary value.",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                                            "description": "Gift card emission date."
É a mesma coisa que creation date? Talvez valha explicar aqui.

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "***********ASDQ"
Qual é a diferença entre redemption token e redemption code?

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "Gift card current balance. For Gift Cards newly created, the balance will be 0.0.",
```suggestion
                        "description": "Gift card current balance. For newly created gift cards, the balance will be 0.0.",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
>                          "type": "integer",
```suggestion
                        "type": "number",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "Field to be filled in when it is not necessary to use a loyalty program for the gift card. Observation: A new `relationNamevalue` is required for each new gift
```suggestion
                        "description": "Field to be filled in when it is not necessary to use a loyalty program for the gift card. Note that a new `relationNamevalue` is required for each new gift card to be created.",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "Programa Vtex Fidelidade"
```suggestion
                        "example": "VTEX Loyalty Program"
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "cards/954/transactions"
Talvez faça sentido na descrição dessa propriedade explicar melhor a estrutura dessa URL. No exemplo, 954 é a ID do gift card?

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +						"description": "Minimum of six characters.",
```suggestion
						"description": "Redemption code, which should have at least six characters.",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +						"description": "Minimum of six characters.",
Tem um limite máximo?

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "The ID of the SKU in VTEX platform.",
```suggestion
                        "description": "SKU ID.",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "Array of price tags, each of which, modifies the price in some way, like discounts or rates that apply to the item in the context of the order.",
```suggestion
                        "description": "Array of price tags, each of which modifies the price in some way, like discounts or rates that apply to the item in the context of the order.",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "`true` if the customer is a legal entity.",
```suggestion
                        "description": "Defines if the customer is a company (`true`) or not (`false`).",
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "miguel scott"
```suggestion
                        "example": "Michael Scott"
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "miguel"
```suggestion
                        "example": "Michael"
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "scott"
```suggestion
                        "example": "Scott"
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "miguel.scott96@yahoo.com.br"
```suggestion
                        "example": "michael.scott96@mail.com"
```

2023-09-27 21:50 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "example": "Credit"
O example está em sentence case, mas na description está em lowercase. Qual dos dois é o padrão?

2023-09-27 22:01 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "example": "Credit"
Boa! O correto é sentence case mesmo, irei corrigir a descrição.

2023-09-27 22:13 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +        "description": ">ℹ️ Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for develo
Boa! Sua dúvida fez sentido sim. Vou modificar a ordem para ficar mais claro que o Reusable está associado ao multipleRedemptions.

2023-09-27 22:18 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                                            "description": "Gift card emission date."
Isso mesmo. Vou modificar para "Gift card creation date".

2023-09-27 22:27 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "example": "***********ASDQ"
- "redemptionToken":  é um código interno do gift card. 

- "redemptionCode: é o próprio código de resgate do vale utilizado pelo cliente no checkout.

2023-09-27 22:39 UTC, ricardoaerobr commented on VTEX - Giftcard API.json
> +                        "example": "cards/954/transactions"
Modificado.

2023-09-27 22:55 UTC, julia-rabello approved these changes

2023-09-27 22:55 UTC, julia-rabello commented on VTEX - Giftcard API.json
> +                        "description": "Gift card resource URL. The first number described in the URL refers to the gift card identification. The second number, refers to the transaction identificati
```suggestion
                        "description": "Gift card resource URL. The first number described in the URL refers to the gift card identification. The second number refers to the transaction identification.",
```

2023-09-28 13:07 UTC, julia-rabello approved these changes

2023-09-28 13:11 UTC, merged